### PR TITLE
Analytics: report User ID

### PR DESCRIPTION
**Pull request by adekbadek**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Enables using the [User ID feature](https://support.google.com/analytics/answer/3123666) of Google Analytics.

### How to test the changes in this Pull Request:

1. In Site Kit -> Settings -> Analytics, edit the "Excluded from Analytics" setting to not exclude logged-in users
2. In your GA account, enable User ID by following steps 1 and 3 from [this docs page](https://support.google.com/analytics/answer/3123666)
3. Visit the site as a logged in user, verify that the visit is reported in the new GA reporting view

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by dkoo** [comment]
@adekbadek I see the page views being reported in my new view. How do I find the user ID being reported in the GA dashboard?

**Comment by adekbadek** [comment]
> How do I find the user ID being reported in the GA dashboard?

Huh, not sure if that's something offered by GA – the promise of User ID is that visits from different browsers will be assigned to a single user, not that you can look up their IDs.

**Review by dkoo — APPROVED** [review]
> Huh, not sure if that's something offered by GA – the promise of User ID is that visits from different browsers will be assigned to a single user, not that you can look up their IDs.

Got it—then I guess seeing the visit being logged in the User-ID view is enough to confirm that it's working, right?

**Comment by adekbadek** [comment]
> Got it—then I guess seeing the visit being logged in the User-ID view is enough to confirm that it's working, right?

I'd say so. Just following GA's docs here :D

**Pull request merged**
