### PR TITLE
Fix/perfmatters defaults adjustments

### PR DESCRIPTION
**Pull request by adekbadek**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

- Removes feature flag on Perfmatters defaults (https://github.com/Automattic/newspack-plugin/pull/2156)
- Updates the defaults
- Removes superflous use of [`default_option_perfmatters_options` filter](https://github.com/WordPress/wordpress-develop/blob/6.1/src/wp-includes/option.php#L188) – `option_perfmatters_options` filter is [ran anyway later](https://github.com/WordPress/wordpress-develop/blob/6.1/src/wp-includes/option.php#L253).

### How to test the changes in this Pull Request:

1. Install the Perfmatters plugin
2. Observe that the defaults are applied (see https://github.com/Automattic/newspack-plugin/pull/2156)

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Review by leogermani — APPROVED** [review]
Works for me. The only comment I have is that we are not actually setting defaults, we are overwriting the plugin settings.

So when we activate Perfmatters, our defaults are applied, but we can't change it. I wonder if we should explain this better. For example we could add a Notice to the Perfmatters admin page saying that Newspack is overwritting some of those params?

**Comment by adekbadek** [comment]
Good idea, added a notice in 604be7e17644ad44f76c478b5f7904239c394b9b

image

**Comment by earcos** [comment]
@leogermani adding all the Newspack CSS files to the exclude CSS list beats part of the purpose of Perfmatters and LCP values on Google Search Console are beyond what Google considers acceptable (2.5+ seconds).

What's the best way to add the `NEWSPACK_IGNORE_PERFMATTERS_DEFAULTS` flag?

Thanks a lot

**Comment by adekbadek** [comment]
That would be in your `wp-config.php` file. If you're a Newspack customer, a TAM or developer can do that for you.

**Pull request merged**
