### PR TITLE
fix: sql error with starter content queries

### PR DESCRIPTION
**Pull request by dkoo**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

I'm not sure when this started or what changed, but I've started seeing an SQL syntax error in the WP dashboard in my local test site. I think this is due to a malformed SQL query due to improper placeholders in a `$wpdb->prepare` statement. There's no need to print `'` single quotes as any strings replacing a placeholder are automatically wrapped in quotes by `$wpdb->prepare`.

### How to test the changes in this Pull Request:

Visit the Newspack dashboard and confirm that you don't see any errors like this:

> WordPress database error You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '_newspack_starter_content_post_'%'' at line 1 for query SELECT post_id FROM wp_postmeta WHERE meta_key LIKE '%'_newspack_starter_content_post_'%'; made by require_once('wp-admin/admin-header.php'), do_action('admin_enqueue_scripts'), WP_Hook->do_action, WP_Hook->apply_filters, Newspack\Engagement_Wizard->enqueue_scripts_and_styles, Newspack\Wizard->enqueue_scripts_and_styles, Newspack\Starter_Content::has_created_starter_content, Newspack\Starter_Content_Provider::has_created_starter_content

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Review by adekbadek — APPROVED** [review]

**Review by leogermani — CHANGES_REQUESTED** [review]
I don't see the errors on my dashboard.

Your proposed fix actually modifies the query by removing the wildcards from the LIKE statements... is that intentional?

You are removing the `%` from the string to look for. I think this breaks the query.

```
$x = '_newspack_starter_content_post_';

# Current code:
echo $wpdb->prepare( "SELECT post_id FROM $wpdb->postmeta WHERE meta_key LIKE '%%%s%%';", $x );
SELECT post_id FROM wp_postmeta WHERE meta_key LIKE '{1995564f6a1faff03f12e8011b146fb4612a15e25cfd420cd420256af3922cf4}_newspack_starter_content_post_{1995564f6a1faff03f12e8011b146fb4612a15e25cfd420cd420256af3922cf4}';

# Your code:

echo $wpdb->prepare( "SELECT post_id FROM $wpdb->postmeta WHERE meta_key LIKE %s;", $x );
SELECT post_id FROM wp_postmeta WHERE meta_key LIKE '_newspack_starter_content_post_';

# Alternative:
$y = '%' . $x . '%';
echo $wpdb->prepare( "SELECT post_id FROM $wpdb->postmeta WHERE meta_key LIKE %s;", $y );
SELECT post_id FROM wp_postmeta WHERE meta_key LIKE '{1995564f6a1faff03f12e8011b146fb4612a15e25cfd420cd420256af3922cf4}_newspack_starter_content_post_{1995564f6a1faff03f12e8011b146fb4612a15e25cfd420cd420256af3922cf4}';

**Comment by dkoo** [comment]
> Your proposed fix actually modifies the query by removing the wildcards from the LIKE statements... is that intentional?

Thanks for the catch—it is not intentional! I'll test your suggestion to see if it fixes the errors on my end.

**Review by leogermani — APPROVED** [review]
Looks good

Nitpick (perhaps not related to this PR). Since this is a prefix, looks like we only need the wildcard after it, and not also at the beginning. We also don't need the `;` at the end

**Comment by dkoo** [comment]
@leogermani Like this? abb3d2f7

**Comment by leogermani** [comment]
> @leogermani Like this? [abb3d2f](https://github.com/Automattic/newspack-plugin/commit/abb3d2f7d9bcf0281df701ff2946ae2eb9c16ea6)

Yes!

I confirmed in my local database that it's returning the same results

**Comment by dkoo** [comment]
Thanks for the review!

**Pull request merged**
