### PR TITLE
feat/campaigns wizard modal

### LINKED ISSUE #926: Campaigns Wizard UI: tag filtering
**Describe the issue**

Now that [tag filtering has been fixed in the Campaigns plugin](https://github.com/Automattic/newspack-popups/pull/506), that functionality is currently a bit hidden with the only indication that you can filter by tag being the Tags panel in the editor page for prompt. We should add UI for this in the Campaigns wizard alongside category filtering. However, the submenus are getting a bit cluttered, so @thomasguillot [suggests a third submenu](https://github.com/Automattic/newspack-popups/pull/506#issuecomment-811757278) specifically for filtering options to contain both category and tag filter fields.

### PR DESCRIPTION
**Pull request by adekbadek**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

@brianboyer - please have a look. Apart from the UI changes there's some improved messaging, which should help users with dealing with the complexity of this product. 

Before - a popover:

image

After - a modal:

image

Closes #926.

### How to test the changes in this Pull Request:

1. Switch to `fix/add-option-setting` branch of `newspack-popups` (https://github.com/Automattic/newspack-popups/pull/588)
1. Visit the Campaigns Wizard, click on the settings icon on a prompt action card
2. Observe a modal being displayed
3. Change the settings, observe the prompt is updated

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by thomasguillot** [comment]
Design-wise, let's merge it as is. I will try to find some time this week to adjust the modal in a separate PR.

**Review by miguelpeixe — CHANGES_REQUESTED** [review]
The `CategoryAutoComplete` component seems to have an issue with the modal, specifically with the `width` of the components label (which is as button element) that is bleeding outside of the modal bounds. My guess is this is what @thomasguillot is referring to?

I also wonder if a `Save` button would be more appropriate for this UI. The save-on-change makes sense for a popover, but I don't think as much for a modal approach. I'd like a take from @thomasguillot for this as well.

**Comment by adekbadek** [comment]
> The CategoryAutoComplete component seems to have an issue with the modal, specifically with the width of the components label (which is as button element) that is bleeding outside of the modal bounds. 

@miguelpeixe  could you provide a screenshot? I can't see that locally.

**Comment by thomasguillot** [comment]
> also wonder if a `Save` button would be more appropriate for this UI.

Really good suggestion, +1

**Comment by miguelpeixe** [comment]
> @miguelpeixe could you provide a screenshot? I can't see that locally.

My Devtools visually placed the element on top of the `CategoryAutoComplete` label, which made me blame the component's label. But actually, it is the modal close button that is bleeding out of the model area:


https://user-images.githubusercontent.com/820752/127015090-1a6806fb-a07a-4aa0-9b60-5c551afc9382.mov

**Comment by brianboyer** [comment]
Really like this! The new help text should be very, um, helpful. :)

**Comment by adekbadek** [comment]
> is the modal close button that is bleeding out of the modal area:

@miguelpeixe - fixed in 3408bf19d9bb3056d129c8ab76969543c68e9c92

**Comment by adekbadek** [comment]
> also wonder if a Save button would be more appropriate for this UI.

Added in cee9e18a2e87de44590f1b499f51af085804c9ec, but it requires https://github.com/Automattic/newspack-popups/pull/588

**Review by miguelpeixe — APPROVED** [review]
Nice! Thank you for the updates 💯

**Pull request merged**
