### PR TITLE
fix(webhooks): check if endpoint exists

### PR DESCRIPTION
**Pull request by adekbadek**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes a small webhooks issue. 

### How to test the changes in this Pull Request:

1. Create a webhook in the Engagement wizard and then delete it 
2. Trigger an action
3. On `master`, PHP will warn that `$endpoint` is null or empty
4. On this branch, there should be no such warnings

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Review by miguelpeixe — CHANGES_REQUESTED** [review]
Thank you for catching that!

On a further look, looks like we need to return early here instead of checking twice if `$endpoint` exists. The previous conditional block should actually `return;` after calling `kill_request()`. The same goes for the `disabled` block you're tweaking.

Does that make sense to you?

**Comment by adekbadek** [comment]
It does, like so? 14e94625058d11cb8b633cae32b8dc6a6e8a6e1a

**Comment by miguelpeixe** [comment]
Yes! The first change becomes superfluous then because on `! $endpoint` it'll return.

**Review by miguelpeixe — APPROVED** [review]
Thank you!

**Pull request merged**
