### PR TITLE
Add NTG events for Coral

### PR DESCRIPTION
**Pull request by yogeshbeniwal**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Add NTG events for Coral.

### How to test the changes in this Pull Request:

1. Checkout add/ntg-events-for-coral branch
2. Configure Coral for comments
3. Submit comment on non-AMP page and see an event trigger with an event_name of `comment added`
4. Repeat for AMP page

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by dkoo** [comment]
@yogeshbeniwal Thanks for the PR! We've discussed this as a team, and it's our view that we'd like to move away from implementing events for specific platforms beyond Google's directly within the code. Instead, we've provided this filter that you and other devs can use to add on your own events: https://github.com/Automattic/newspack-plugin/blob/master/includes/class-analytics.php#L327

Would this be sufficient to add Coral tracking for your purposes? If so I'll close #587. Thanks!

**Comment by yogeshbeniwal** [comment]
@dkoo That's a good approach. Can you pls assist with a sample for this filter e.g. for Coral, Team then can use it for other platforms also.

**Comment by dkoo** [comment]
> Can you pls assist with a sample for this filter e.g. for Coral, Team then can use it for other platforms also.

@yogeshbeniwal Sure, here's a simple example. Put this in a custom plugin or wherever you're executing custom code for your sites (modify as needed to make it a method on an existing class or to namespace it):

```
/**
 * Add custom events to be reported to Google analytics.
 * 
 * @param array $events Array of analytics events config. Each item should contain the following properties:
 *              $events['id']              A unique string to identify this event. For exmaple, `'n' . substr( uniqid(), 10 )`
 *              $events['amp_on']          The action to trigger the event via AMP Analytics on AMP pages.
 *                                         See https://amp.dev/documentation/components/amp-analytics/?format=websites for more info.
 *              $events['on']              The action to trigger the event on non-AMP pages.
 *                                         See https://support.google.com/analytics/answer/1033068?hl=en#zippy=%2Cin-this-article for more info.
 *              $events['element]          The selector for the element that will trigger the action.
 *              $events['event_name']      The event name reported to GA.
 *              $events['event_category']  The event category reported to GA.
 *              $events['event_label']     The event label reported to GA.
 *              $events['non_interaction'] Optional. If true, the event will be reported as a non-interaction event.
 *                                         See https://support.google.com/analytics/answer/1033068?hl=en#NonInteractionEvents&zippy=%2Cin-this-article for more info.
 */
function newspack_analytics_events_add_coral( $events ) {
	// Note: $some_condition must be defined.
	if ( $some_condition ) {
		$events[] = [
			'id'             => self::get_uniqid(),
			'amp_on'         => 'amp-form-submit-success',
			'on'             => 'submit',
			'element'        => '#comments-postCommentForm-form',
			'event_name'     => 'comment added',
			'event_category' => 'NTG user',
			'event_label'    => get_the_title(),
		];
	}

	return $events;
}
add_filter( 'newspack_analytics_events', 'newspack_analytics_events_add_coral' );
```

Some notes on the above:

* The `newspack_analytics_events` filter is applied on the `wp_footer` action hook, so if you don't define `$some_condition` any changes you make to the `$events` array will happen on every page that runs `wp_footer`.
* In your case you will want to define `$some_condition` to modify `$events` only on pages that render a Coral comment form. I don't know all the conditions where this will happen so I'll leave that logic to you.

**Comment by yogeshbeniwal** [comment]
Thanks @dkoo. Will wait for another ongoing discussion before testing this i.e. disable Newspack events if Site Kit's GTM module is active.

**Comment by dkoo** [comment]
> Thanks @dkoo. Will wait for another ongoing discussion before testing this i.e. disable Newspack events if Site Kit's GTM module is active.

@yogeshbeniwal #1216 should have accomplished this. Can you please confirm, and if the [event filtering](https://github.com/Automattic/newspack-plugin/pull/1219#issuecomment-970489914) works for your use case?

**Comment by yogeshbeniwal** [comment]
@dkoo That PR actually disables NTG events, waiting for it to be enabled. Please see latest comment at https://github.com/Automattic/newspack-popups/pull/657#issuecomment-970275131

**Comment by adekbadek** [comment]
@yogeshbeniwal – with https://github.com/Automattic/newspack-plugin/pull/2149 merged, you should be able to insert the events with Newspack's filter also when having GTM configured.

**Pull request closed without merging**
