### PR TITLE
feat: replace recommended cookie plugin

### PR DESCRIPTION
**Pull request by adekbadek**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

For when we're ready to switch from recommending [WP GDPR Cookie Notice](https://wordpress.org/plugins/wp-gdpr-cookie-notice/) to [Complianz](https://wordpress.org/plugins/complianz-gdpr/).

Context: pamTN9-4wk-p2

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by gamebits** [comment]
We can move forward with this, per 1200024937525366-as-1201693786874162.

**Review by dkoo — COMMENTED** [review]
@gamebits I updated this outdated branch against `master` and also updated the plugin description with the latest iteration on the [plugin page](https://wordpress.org/plugins/complianz-gdpr/).

I noticed that the WP GDPR Cookie Notice plugin was included in the list of "supported but not managed" third-party plugins, meaning it won't appear in the plugins list unless installed, but also won't throw any warnings in the Health check. So I also added Complianz here, as it seems to be a one-to-one replacement for WP GDPR. Do you want to have it appear in the plugins list alongside recommended plugins like WooCommerce?

**Comment by gamebits** [comment]
@dkoo WP GDPR Cookie Notice already appears alongside WooCommerce:

wp-gdpr-cookie

We can have the same behavior for Complianz.

**Comment by dkoo** [comment]
@gamebits I removed it from the "unmanaged" list. Does the behavior match expectations, now?

**Review by gamebits — APPROVED** [review]
LGTM!

**Pull request merged**
