### PR TITLE
feat(reader-data): set referrer

### PR DESCRIPTION
**Pull request by miguelpeixe**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Similar to #2520 and #2539, set the referrer store data item if coming from an external source.

### How to test the changes in this Pull Request:

1. Create a link to your instance from a different domain (use Google Drive, Gmail, or any code playground)
2. Click on the link to visit the site and confirm the referrer is stored (`newspackReaderActivation.store.get( 'referrer' )`)
3. Navigate on the site and confirm the referrer persists (not replaced by referring itself)

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Review by leogermani — COMMENTED** [review]
Looks good but couldn't this be done directly on the front-end?

**Review by leogermani — APPROVED** [review]
Looks good.

What about what we've discussed about keeping the original external referrer when the user navigates to internal pages on the site? Want to address this later?

**Comment by miguelpeixe** [comment]
It should be working like that. It doesn't update if the referrer is empty or it matches the window's location hostname

**Comment by leogermani** [comment]
> It should be working like that. It doesn't update if the referrer is empty or it matches the window's location hostname

ah, you're right!

**Pull request merged**
