### PR TITLE
feat(ras): replace newsletters verification email

### PR DESCRIPTION
**Pull request by miguelpeixe**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Replaces Newspack Newsletters' native email verification with RAS' account verification email when RAS is enabled.

This allows the verification email to take advantage of RAS' customization and the reader to verify their account in a different session/device, which is currently unsupported in Newspack Newsletters' implementation.

### How to test the changes in this Pull Request:

1. With RAS enabled and Newsletters configured with subscription lists, create a new account and verify the account's email
2. Delete the Newspack Newsletter's verification meta: `wp user meta delete {user_id} newspack_newsletters_email_verified`
3. Visit the "Newsletters" page of "My Account" and click to verify
4. Log out
5. Check the received email and confirm it's RAS' verification email
6. Visit the link in a fresh (unauthenticated) session and confirm you get authenticated, verified and redirected to the Newsletters page of "My Account"

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Review by dkoo — CHANGES_REQUESTED** [review]
This flow is very unlikely to occur since it's almost impossible for unverified readers to come across the Newsletters section of My Account, right? But a good change nonetheless.

I ran into some weirdness at step 3:

Screen Shot 2023-07-14 at 2 57 59 PM

**Comment by miguelpeixe** [comment]
It's actually not that unlikely. When the account is created through Woo's checkout it's verified for RAS but not for newsletters (because there was no email verification in the process).

Never came across this double notification issue, but looks like something from `master` since this PR doesn't change this part of the code. I'll take a look and report back soon.

**Comment by dkoo** [comment]
> It's actually not that unlikely. When the account is created through Woo's checkout it's verified for RAS but not for newsletters (because there was no email verification in the process).

Aha, thanks for explaining!

**Comment by miguelpeixe** [comment]
I tried different ways to reproduce the issue with double notification without success:
 - Refreshing the page after submitting (returns no notification)
 - Double-clicking the submit button (no difference)

Are you having the double notification consistently?

**Review by leogermani — APPROVED** [review]
It all works fine for me and no duplicate notices.

image

**Pull request merged**
