### PR TITLE
feat(reader-revenue): add "other" reader revenue platform

### LINKED ISSUE #2059: Reader Revenue Platform: Provide "Other" option
**Is your feature request related to a problem? Please describe.**
Currently, it is possible for sites to select "Newspack" as a Platform in Newspack Reader Revenue although it is not being used (due to choosing to go with a third-party option that is not available in the dropdown or not in use whatsoever). Because of this, incorrect data is pulled when reviewing overall Newspack sites that utilize "Newspack" as a reader revenue platform option.

**Describe the solution you'd like**
Provide a fourth dropdown option such as "Other" or "Third Party" to clearly identify which sites are not using the other available options.

### PR DESCRIPTION
**Pull request by adekbadek**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes #2059.

### How to test the changes in this Pull Request:

1. Visit the Reader Revenue wizard, observe a new option in the platform selection – "Other" 
2. Select it, observe the only available tab is the "Platform" tab
3. Observe any Donate block added will no be rendered on the front-end

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Review by dkoo — CHANGES_REQUESTED** [review]
This works in the dashboard, but it might have wider implications. Most notably, it breaks the Donate block, so we might want to have a check for this in the Blocks repo to not render that block on the front-end if "Other" is the active RR platform.

**Comment by adekbadek** [comment]
I was thinking that any user of the "other" platform would maybe implement their own handling of the Donate block. But that's too ambitious of an assumption. 4af139953fb01988df6b36823420a6e2389bc649 updates the code so the Donate block renders blank if the platforms is set to 'other'.

**Review by dkoo — CHANGES_REQUESTED** [review]
I think this not rendering the Donate block is enough to handle this, for now. The only other thing I'd request is some kind of message in the editor to indicate that the block isn't available/won't be shown on the front-end? My crude mockup (the last line is intended to be a link to the RR wizard):

Screen Shot 2022-12-02 at 11 03 06 AM

**Comment by adekbadek** [comment]
Done in https://github.com/Automattic/newspack-blocks/pull/1323 – the error state already in use will be used:

image

**Review by dkoo — APPROVED** [review]
Works for me!

**Pull request merged**
