### PR TITLE
feat: update RAS settings layout to i3 designs

### PR DESCRIPTION
**Pull request by dkoo**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Updates the design of the new RAS settings page to the latest i3 designs. This PR covers only the first settings page in **Newspack > Engagement > Reader Activation**. The setup wizard for Campaigns defaults will come in a future PR.

Screen Shot 2023-04-03 at 4 04 29 PM

### How to test the changes in this Pull Request:

1. Start with a fresh test site (JN). Install the plugin from this branch and run `wp newspack setup` to scaffold the site with default Newspack settings.
2. Visit **Newspack > Engagement > Reader Activation** to view the checklist of prerequisites that need to be completed before RAS Campaigns defaults can be configured.

Screen Shot 2023-04-03 at 4 11 36 PM

3. Expand each card and complete the setup.
  - For cards that contain fields and a "Save settings" button, fill out the required fields and click "Save" (note that some fields will be prepopulated with suggested settings, but you still need to click "save" to complete the prerequisite). After saving, confirm that a.) the card collapses automatically with a "status: ready" state, and b.) if you re-expand the card, the button label changes to say "Update settings" instead of "Save settings."
  - For cards that link out to a separate page to complete configuration, complete the required config and then go back to the **Newspack > Engagement > Reader Activation** page. Confirm that the card updates to say "status: ready" after completing the required configuration.
4. The last card ("Reader Activation Campaign") is just a placeholder for now. For this PR, just confirm that the action button is disabled with a "Waiting for all settings to be ready" label until all other settings are ready, after which the button should change to an active "Set up Reader Activation campaign" button which currently does nothing but will redirect to the prompt setup wizard in a future PR.
5. Also confirm that the "Complete the settings to enable Reader Activation" banner at the top of the page disappears after you complete all steps (in a future PR this will happen only after you complete the not-yet-existent prompt setup wizard).
6. Expand the Advanced Settings panel and confirm that the "Save advanced settings" button now only saves changes from the fields in advanced settings, not elsewhere on the page.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Review by laurelfulford — APPROVED** [review]
This looks good to me overall, @dkoo!

Starting from a fresh JN site, the "Set up Reader Activation campaign" button is greyed out, and the "Complete the settings..." banner displayed at the top.

As I completed each step (or saved the options that were already filled out), the panel correctly indicated it was done.

And once all panels were checked, the "Set up Reader Activation campaign" turned blue and active, and the "Complete the settings...." banner went away. 

Lastly, the Advanced Settings all look good, and didn't duplicate anything in the action cards!

Visually, I did notice that the spacing in the in-panel settings are slightly different than the mock-ups -- the paragraph at the top has more space below it, and the button has less above it. This looks like it's all coming from existing component styles, and not something that changed in this PR, though -- so if we do change it, it's probably best handled separately, taking the whole plugin into account. 

Screenshot:
Screen Shot 2023-04-06 at 12 19 17 PM

Mockup (well, screenshot of the mockup 🙂):
Screen Shot 2023-04-06 at 3 15 13 PM

Lastly I don't think my run-through was standard (since I was doing _all_ the steps back to back, and actual sites will probably have some of these set up already), but it did feel like there should be a 'Back' button or some way to return to the Reader Activation screen when you jump away from it to complete a step. I knew how to get back, but some less familiar users may not. Definitely getting into the weeds a bit with that though -- this may be a wizard-wide thing, and I have no idea how complicated it'd be to only show in cases like this when you're going from one wizard screen to another!

Anyway! Giving this a 👍 since it's working as expected; I'm going to spin up a separate issue for the spacing feedback, in case that's an easy (non-destructive) change for the plugin for down the road!

**Comment by dkoo** [comment]
@laurelfulford thanks for the review and the feedback on the spacing within the cards! Before we file a new issue to change the spacing, we should check with @evilluendas about whether it's necessary or if these cards can just inherit styles from the existing components.

> it did feel like there should be a 'Back' button or some way to return to the Reader Activation screen when you jump away from it to complete a step.

That's great feedback—I'll drop into the design thread.

**Comment by laurelfulford** [comment]
> we should check with @evilluendas about whether it's necessary or if these cards can just inherit styles from the existing components.

Ah, that's a great point @dkoo! 😅  I _may_ have jumped the gun and created 1200550061930446-as-1204352026586264, but it's assigned to me with a low priority, so I can leave it unless I'm asked to act on it!

**Comment by evilluendas** [comment]
Hi! Quick reply just based on the screenshots: I think the spacing in the designs look better and more balanced, but I think adding customizations for this specific case isn't really worth it. 

I'd use the inherited styles at the moment, and then eventually (as a separate project) do a sweep to the base styles to improve them everywhere. Makes sense?

**Comment by dkoo** [comment]
Thanks, @evilluendas—makes perfect sense!

**Pull request merged**
