### PR TITLE
feat: segments criteria ui

### PR DESCRIPTION
**Pull request by miguelpeixe**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

1204189396255901-as-1204857763418497

Changes the Segments UI to use the new criteria system and updated schema.

### How to test the changes in this Pull Request:

Confirm updated tests are passing and have appropriate coverage.

1. Checkout this branch and https://github.com/Automattic/newspack-popups/tree/epic/rearchitecture
2. Create, edit and delete segments and confirm everything works as expected
3. Create a segment using all available criteria
4. Visit the "Segments" home and confirm the description renders correctly for every item
5. Visit the "Campaigns" home and confirm the same description also renders correctly

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by leogermani** [comment]
@miguelpeixe 

https://github.com/Automattic/newspack-plugin/pull/2537/commits/14761601f8cb63a393857549f3343eab055688d9 fixes an issue that criteria was being deleted if you toggled the status from the segments list. -> Note that this will only work after the segment was migrated. But I think that's fine, we will run the migration for all segments soon.

https://github.com/Automattic/newspack-plugin/pull/2537/commits/e293da105dd69c3375332a6558652d55e03b1f85 fixes an issue that the Save button was not being enabled if you toggled the status from the segment page

and https://github.com/Automattic/newspack-plugin/pull/2537/commits/bbd5d9fe37566329c0a36591879cbf7da767d23e gets rid of some warnings

Is there anything else you want to address here? I think it's good to go

**Comment by miguelpeixe** [comment]
Thanks for the fixes!

> Is there anything else you want to address here? I think it's good to go

I'm still working on the draft to make sure all wizard screens understand the new criteria system. It's still not working well when rendering the segment description on the `SegmentGroup` component (Campaigns tab)

I'll place it for code review when it's ready, it should go through regular code review before merging to the epic branch.

**Comment by miguelpeixe** [comment]
@leogermani can you show me the warnings that warranted bbd5d9fe37566329c0a36591879cbf7da767d23e? I'm not getting any in my instance and it should be handled already by returning `null` with `getCriteriaValue()`.

**Comment by leogermani** [comment]
> @leogermani can you show me the warnings that warranted [bbd5d9f](https://github.com/Automattic/newspack-plugin/commit/bbd5d9fe37566329c0a36591879cbf7da767d23e)? I'm not getting any in my instance and it should be handled already by returning `null` with `getCriteriaValue()`.

Example:

```
Warning: `value` prop on `select` should not be null. Consider using an empty string to clear the component or `undefined` for uncontrolled components.
```

**Comment by miguelpeixe** [comment]
Thanks! For some reason, I'm not getting that warning. I changed the handling so the function doesn't return the unhandled value 8e0193c92751b774cb26ecd76cc77332ca724ccd.

**Comment by miguelpeixe** [comment]
@dkoo [commented](https://github.com/Automattic/newspack-popups/pull/1159#pullrequestreview-1538145518):

> I ran into an issue when editing an existing segment. Updating the select dropdown values doesn't always update the isDirty state, so the "Save" button remains disabled until you edit another field. Editing other types of fields seems to work as expected, and the issue is intermittent with dropdowns. I'm approving this PR because I think the issue is coming from https://github.com/Automattic/newspack-plugin/pull/2537, not this one.

**Review by dkoo — CHANGES_REQUESTED** [review]
Looks good, and mostly works! The only thing is [this](https://github.com/Automattic/newspack-plugin/pull/2537#issuecomment-1642862965) is still happening for me. Replication steps:

1. Create a new segment and set all the of the select dropdowns to something other than the default. Save.
2. Edit the segment again. Change the values of the dropdowns to another value that is not the default. Observe that the "Save" button doesn't become active.
3. If you add `console.log( segmentCriteriaInitially, segmentCriteria );` to https://github.com/Automattic/newspack-plugin/pull/2537/files#diff-a975ee831b86af1483494488d751b64b384c16269ad9450f03c7c697606548d1 right where `isDirty` is being defined, you'll see that the values of `segmentCriteriaInitially` are somehow being updated on change, so `isDirty` is set to `false`.

**Comment by miguelpeixe** [comment]
Good catch! e293da105dd69c3375332a6558652d55e03b1f85 changed a strategy that was using `JSON.stringify()` instead of  `[ ...array ]` cloning for checking criteria changes.

Fixed with 76421c70667793fda7e662b9f5f519e4671510d2

**Review by dkoo — APPROVED** [review]
That did it!

**Pull request merged**
