### PR TITLE
feat: add anonymized email to ga4 events

### PR DESCRIPTION
**Pull request by leogermani**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Adds an anonymized email para to GA4 events.

### How to test the changes in this Pull Request:

1. Set up a site with GA4 back end events (Newspack > Analytics > Newspack Custom Events)
2. Fire a back-end event by registering via the registration block, making a donation or subscribing to a newsletter
3. In GA, confirm you see the event coming through and that it has the new `user_hash` param

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by miguelpeixe** [comment]
Maybe `email_hash` is more accurate? I'd assume a `user_hash` wouldn't change, but in theory, a user could change their email (even if we don't support email changes now)

**Comment by miguelpeixe** [comment]
@leogermani ping ⬆️

**Comment by leogermani** [comment]
> Maybe `email_hash` is more accurate? I'd assume a `user_hash` wouldn't change, but in theory, a user could change their email (even if we don't support email changes now)

yep, at first I was thinking of using the email in conjunction with the ID, or the site name, or something tat would tell this email appart from the same email used in another site. But then I figured only the email looks ok, wdyt?

**Review by miguelpeixe — APPROVED** [review]
Works well!

> email in conjunction with the ID, or the site name, or something tat would tell this email appart from the same email used in another site

Isn't a different site a different GA property?

**Pull request merged**
