### PR TITLE
feat: campaign group filter

### PR DESCRIPTION
**Pull request by jeffersonrabb**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Adds UI to filter campaigns by campaign group taxonomy.

Dependent PRs: 
~https://github.com/Automattic/newspack-plugin/pull/764~
~https://github.com/Automattic/newspack-plugin/pull/767~
~https://github.com/Automattic/newspack-plugin/pull/768~

Screen Shot 2021-01-04 at 8 30 56 AM

### How to test the changes in this Pull Request:

1. Make sure there are several Campaign Group taxonomy terms created, which can be done by editing any campaign and using the Campaign Groups sidebar panel.
2. In the Campaigns Wizard, observe `Campaign groups` `SelectControl`. Verify it contains all campaign groups. 
3. Change the selected campaign group, verify that visible campaigns are filtered correctly.
4. Change back to `All Campaigns`, verify all campaigns are shown again.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by jeffersonrabb** [comment]
UI updates suggested by @thomasguillot made in https://github.com/Automattic/newspack-plugin/pull/769/commits/a91ac7feecd3f91a981f7ebe164717632a9a5a9c

**Review by thomasguillot — APPROVED** [review]
Looks good.

**Review by dkoo — COMMENTED** [review]
This looks good from a functional testing standpoint; awaiting conflict resolution to review the code.

**Comment by jeffersonrabb** [comment]
> This looks good from a functional testing standpoint; awaiting conflict resolution to review the code.

Conflicts are resolved. https://github.com/Automattic/newspack-plugin/pull/769/commits/ce143154b25ef9febc3ab45333fd75469e7813df was necessary because the[ localized taxonomy slug](https://github.com/Automattic/newspack-popups/blob/master/includes/class-newspack-popups.php#L362) is only made available in the editor. I'm not sure why it worked in our testing earlier, but I'll try to resolve this another way in a later PR.

**Review by dkoo — CHANGES_REQUESTED** [review]
Code looks good, but after some further testing there are a couple of minor quality-of-life items I'd like to request:

1. The dropdown can take a few seconds to load all the Campaign Groups, so if you click on it right after the page load you might not see all of them at first. Could we disable the dropdown or put it into a loading state until the taxonomies are fetched?
2. If you filter by a Campaign Group, then delete all of the campaigns in that group, you are met with an empty list. Could we show an "empty" message if the selected filter shows no results?

And a question which might also be relevant for the `master` branch: if you delete a campaign, it presumably gets sent to trash. But since we're hiding the regular WP posts list UI for campaigns, there's no way to see trashed campaigns to restore them. Should we consider adding a filter to the Campaigns wizard UI to show trashed campaigns, with the option to restore them to draft status?

**Comment by jeffersonrabb** [comment]
> 1. The dropdown can take a few seconds to load all the Campaign Groups, so if you click on it right after the page load you might not see all of them at first. Could we disable the dropdown or put it into a loading state until the taxonomies are fetched?

Added a loading state for the `SelectControl` (disabled, text: "Loading...") in https://github.com/Automattic/newspack-plugin/pull/769/commits/b493fec0ea5139e7c9d7eaa0a782f9ff1308a1c2 and https://github.com/Automattic/newspack-plugin/pull/769/commits/085c50e3f2f1365cb3994216ea5bb7f0095339e0

**Comment by jeffersonrabb** [comment]
> 2\. If you filter by a Campaign Group, then delete all of the campaigns in that group, you are met with an empty list. Could we show an "empty" message if the selected filter shows no results?

Good point! Resolved in https://github.com/Automattic/newspack-plugin/pull/769/commits/6c11d84635c1cbb94235e29dbfe562e3c3313007

**Comment by jeffersonrabb** [comment]
> And a question which might also be relevant for the `master` branch: if you delete a campaign, it presumably gets sent to trash. But since we're hiding the regular WP posts list UI for campaigns, there's no way to see trashed campaigns to restore them. Should we consider adding a filter to the Campaigns wizard UI to show trashed campaigns, with the option to restore them to draft status?

I think this exceeds the scope of this PR but it's a great question. Could you file an issue so we can track it?

**Comment by dkoo** [comment]
> I think this exceeds the scope of this PR but it's a great question. Could you file an issue so we can track it?

Issue filed as #784.

**Review by dkoo — APPROVED** [review]
Looks good now, thanks for the updates!

**Pull request merged**
