### PR TITLE
Fix: campaigns-wizard: prevent edge case errors

### PR DESCRIPTION
**Pull request by adekbadek**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes small edge case errors

### How to test the changes in this Pull Request:

1. Create two campaigns, a one a draft and one in test mode 
2. In Campaigns Wizard, observe that neither has the "Sitewide default" toggle in the options popover
3. Assign a category to the draft campaign, observe there is no error and the category is assigned
4. Repeat 3. with the test mode campaign

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by dkoo** [comment]
> Assign a category to the draft campaign, observe there is no error and the category is assigned

At this step, I get an overlay error message `The campaign specified does not exist` and a console error that the `POST` request returned a 500 error (hard to see because it shows for only a split second). Then I get immediately redirected to the main Newspack dashboard page.

**Review by dkoo — CHANGES_REQUESTED** [review]
Related to the error message, the function `retrieve_popup_by_id` in the campaigns plugin only returns published campaigns: https://github.com/Automattic/newspack-popups/blob/master/includes/class-newspack-popups-model.php#L266

Maybe need a patch there to accompany this one?

**Comment by adekbadek** [comment]
@dkoo 

> Maybe need a patch there to accompany this one?

Exactly, I did that in https://github.com/Automattic/newspack-popups/pull/214, but for some reason though these PRs might be tested separately

**Review by dkoo — APPROVED** [review]
Awesome, I missed that one somehow. Works well with the Campaigns patch. 👍

**Pull request merged**
