### PR TITLE
feat: use newspack manager plugin for authentication

### PR DESCRIPTION
**Pull request by adekbadek**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Changes how the Google OAuth and Fivetran proxies authenticate. Not by passing a WPCOM token anymore, but with an API key.
Note that this requires corresponding changes in the proxies.

### How to test the changes in this Pull Request:

1. Ensure you have the option* set to the correct value
2. Observe the Google and Fivetran connections working as expected
3. Remove the option, observe the aforementioned connections are not available in the Connections wizard
4. Change the option value to an invalid one, observe the proxies return error and disallow connection
5. Disconnect WPCOM. Observe the other services can be connected regardless of WPCOM connection status

\* Name is defined in another part of the software, as `NEWSPACK_MANAGER_API_KEY_OPTION_NAME` env variable

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1201344639817758

### CODE REVIEW

**Review by miguelpeixe — CHANGES_REQUESTED** [review]
The `apiFetch()` does not resolve the `inFlight` state in case of error. `setInFlight( false );` should be placed inside the `finally()` method of the promise for both Fivetran and Google.

The following check will probably have to change too, since WPCom connection is no longer required for the other connections.
https://github.com/Automattic/newspack-plugin/blob/master/includes/wizards/class-connections-wizard.php#L90-L97

**Comment by adekbadek** [comment]
> The apiFetch() does not resolve the inFlight state in case of error. setInFlight( false ); should be placed inside the finally() method of the promise for both Fivetran and Google.

Fixed in 2557025dfc7dd839d27d6040311c61b938e292fa

> The following check will probably have to change too, since WPCom connection is no longer required for the other connections.

Updated in 9c5b7a9

**Review by miguelpeixe — APPROVED** [review]
🎉

**Comment by adekbadek** [comment]
Note that these changes require updated code on the proxy site. Once changes from this PR are live, the proxy site should be updated.

**Pull request merged**
