### PR TITLE
feat: redesign OTP flow

### PR DESCRIPTION
**Pull request by miguelpeixe**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Implements the functional changes required for the redesign in progress. The UI should be updated once #2809 is merged.

| Before | After |
| --- | --- |
| image | image |
| image | image | 

The PR focuses primarily on implementing the "Resend code" button and its required functionality. Additionally:

 - Switched the order for the third-party authentication to render first
 - Prevent third-party auth to appear on the OTP code form
 - Updated OTP copy
 - Updated error message position

### How to test the changes in this Pull Request:

1. Check out this branch and go through the magic link/OTP flow for an existing reader
2. Confirm the new UI as shown in the image above and the "Resend code" counts down in a disabled state
3. Confirm the button is reenabled after the timer is done
4. Click to Resend Code and confirm the code is sent and the timer is back
5. Click "Back" and confirm you're back on the initial state of the form

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Review by leogermani — CHANGES_REQUESTED** [review]
After I resend the code, the "Continue" button becomes unresponsive. I click it and nothing happens

**Comment by miguelpeixe** [comment]
Any js errors?

**Comment by leogermani** [comment]
> Any js errors?

no, nothing

**Comment by miguelpeixe** [comment]
Fixed in 690cc732637f5e91d804d1b8118dab35e8e9ca23. Forgot to reenable the submit buttons after the "resend code" is complete.

**Review by leogermani — APPROVED** [review]

**Pull request merged**
