### PR TITLE
feat: add a sticky ad slot to the Advertising wizard

### PR DESCRIPTION
**Pull request by dkoo**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Adds a new pre-defined sticky ad slot to the Advertising wizard. Test alongside https://github.com/Automattic/newspack-theme/pull/1208.

Closes https://github.com/Automattic/newspack-theme/issues/1199.

### How to test the changes in this Pull Request:

1. Check out this branch and run `npm run build`.
2. Go to **Newspack > Advertising** and make sure you have the relevant plugins and service providers configured to display ads.
3. Go to **Global Settings** and confirm there's a new slot for Sticky Ad:

Screen Shot 2021-01-13 at 3 20 51 PM

4. Enable the Sticky Ad slot and choose a provider and ad unit for the slot.
5. View the front-end of the site in both AMP and non-AMP mode. The unit should render in a fixed container at the bottom of the viewport. Note that the ad slot will render based on its ad unit, so it will only appear if the unit is filled.
6. Test the "close" button functionality in both AMP and non-AMP mode. Clicking the X button should hide the ad for the current page view only.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by philipjohn** [comment]
Heh, I got this at first try :) 

Screenshot from 2021-01-14 12-09-57

**Comment by dkoo** [comment]
> Nevermind, I didn't have Ads activated

Strange that you were able to see that error—if you don't have Ads activated, it should prompt you to activate it rather than show the ads UI.

**Review by philipjohn — APPROVED** [review]
Approving this as I've verified it works as expected, and the remaining bits in https://github.com/Automattic/newspack-theme/pull/1208 are well tested by Laurel

**Comment by dkoo** [comment]
> Strange that you were able to see that error—if you don't have Ads activated, it should prompt you to activate it rather than show the ads UI.

Just to close the loop on the above: this is only true if Newspack is not in debug mode. If in debug mode, all installed plugins will be reported as active, even if not actually active, which bypasses the plugin activation prompt and might result in errors like what Phil saw.

**Pull request merged**
