### PR TITLE
Action Card Component

### PR DESCRIPTION
**Pull request by jeffersonrabb**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR adds a new component, `ActionCard`, which can be used any time there is a series of similar items in a wizard. The initial use case will be for the plugin installer, but it's designed to be swapped in to Subscriptions Wizard, Ad Wizards, and many others. The `ActionCard` component takes the following parameters:

`title`: Primary text  display.
`description`: Secondary text display.
`notification`: Optional notification text.
`notificationLevel`: The severity/type of notification (error|warning)
`actionText`: Text for the action button on the right  side.
`secondaryActionText`: Text for the secondary action  button (e.g. Delete)
`image`: Optional path for image to be displayed at the far left.
`imageLink`: Optional URL to link the image to.
`onClick`: Click handler for primary button.
~~`onSecondaryClick`~~ `onSecondaryActionClick`: Click handler for secondary button.
~~`isButton`: Signifies button(s) on the right side (`secondaryActionText`, `onClick`, and  `onSecondaryActionClick` are only meaningful if `isButton` is true)~~
~~`isSpinner`~~ `isWaiting` Signifies waiting state for the component, with a spinner.

Some questions for discussion:

1) Is `ActionCard` the best name for this component? This is loosely similar to the iOS [UITableViewCell](https://developer.apple.com/documentation/uikit/uitableviewcell), which is semantically quite different.
~~2) Is it problematic that `isButton` and `isSpinner` could both be true on the same instance of this component? Would it be preferable to have a prop called `actionCardStyle` which could be button|spinner|static?~~ 
_Update: Refactored in such a way that button state is inferred from the available parameters, leaving only `isWaiting` to be explicitly set._
~~3) The vertical alignment of the right edge is top-aligned if there are primary and secondary buttons, but in no other cases. Is this odd?~~
_Update: By switching from `display: none` to `visibility: hidden` the spacing issue goes away._ 

### How to test the changes in this Pull Request:

1. Check out the branch.
2. `npm ci && npm run clean && npm run build:webpack`
3. Navigate to Newspack->Components Demo, observe seven examples of different `ActionCard` configurations.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by jeffersonrabb** [comment]
> The warning/error notifications are not quite as prominent as we might want them to be. Can we add a background to those, as used for warnings/error notifications within the WordPress plugins screen?

Done in https://github.com/Automattic/newspack-plugin/pull/79/commits/94fc881309fee31a8c1f873b23fbc9736e38a0a8

**Comment by jeffersonrabb** [comment]
> The component with the SecondaryActionText “Delete” should probably have an ActionText of “Active” in grey, since the delete action will only be available when a plugin is already installed/active. You can probably eliminate one instance and combine block 2 and 6.

To match the use case in the Subscriptions Wizard, I instead changed the Action button to "Edit" and left the secondary as "Delete", in https://github.com/Automattic/newspack-plugin/pull/79/commits/a609b2632e50892d023e8a1f07dccbc9e2f5cee4

**Comment by jeffersonrabb** [comment]
> Styling tweak: The delete link should be red and have an underline (indicating it’s a link).

Done in https://github.com/Automattic/newspack-plugin/commit/a609b2632e50892d023e8a1f07dccbc9e2f5cee4. Also renamed the secondary button to "deletion" on the assumption that this button will _always_ be delete.

**Comment by jeffersonrabb** [comment]
> Lastly, some of the interactive elements don't have hover states yet – specifically all active links in the action card region right.

@sonjaleix, what should the hover states be?

**Comment by jeffersonrabb** [comment]
> Also renamed the secondary button to "deletion" on the assumption that this button will always be delete.

I thought better of this and went back to calling it "secondary."

**Comment by jeffersonrabb** [comment]
> Lastly, some of the interactive elements don't have hover states yet – specifically all active links in the action card region right.

Everything should have a hover as of https://github.com/Automattic/newspack-plugin/pull/79/commits/3a53c3b1dc46b9bc662ee642a608769bd4d20143

**Comment by sonjaleix** [comment]
@jeffersonrabb I reviewed the changes and all instances of the component is now looking good!

**Comment by philipjohn** [comment]
Just noting I'll take a look at this too, as I'm expecting to use the component in my Ads wizard :)

**Pull request merged**
