### PR TITLE
Fix/ci build

### PR DESCRIPTION
**Pull request by adekbadek**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Updates `newspack-script` to a version which handles the weird `HookWebpackError: error:0308010C:digital envelope routines::unsupported` error, [as seen here](https://app.circleci.com/pipelines/github/Automattic/newspack-plugin/5484/workflows/41c1fbe0-f1ff-4bff-9949-97e45aaa10dd/jobs/25721/parallel-runs/0/steps/0-105).

Because it's a bump from `4.0.0` to `4.3.6`, there are some other tweaks as well. 

### How to test the changes in this Pull Request:

The real test will be whether the CI job ran on `master` (after this is merged) build the JS files successfully. In the meantime, here's how it can be approximated:

1. Visit [CI for this branch](https://app.circleci.com/pipelines/github/Automattic/newspack-plugin?branch=fix%2Fci-build)
2. Go to the latest `all` workflow and select `build` step
3. Rerun the step with SSH
4. Ensure the step runs to completion, meaning it installs all `npm` dependencies
5. `cd project` and run `npm run build` – observe the files building without error

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Review by leogermani — APPROVED** [review]
Let's merge and watch the CI

**Review by dkoo — APPROVED** [review]
For some reason CircleCI isn't letting me re-run the job, but I did install locally and confirm that the build works. Let's merge this and see if the CI job runs correctly.

**Comment by adekbadek** [comment]
> I did install locally and confirm that the build works

The tricky part is that I haven't been able to reproduce it locally.

**Comment by adekbadek** [comment]
Looks like that worked. [The CI job has produced a ZIP with the JS files](https://app.circleci.com/pipelines/github/Automattic/newspack-plugin/5502/workflows/075700c7-3ceb-45b6-bfeb-02f6e8ec3864/jobs/25807/artifacts), which I've been able to install successfully on a fresh new site.

**Comment by dkoo** [comment]
Thanks for confirming!

**Pull request merged**
