### PR TITLE
fix: hide My Account links if not relevant

### PR DESCRIPTION
**Pull request by dkoo**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/trunk/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

I'm not sure when this changed, but at some point in the past we used to hide "Subscriptions", "Orders", and "Payment Methods" links in the My Account dashboard if the customer didn't have any subscriptions or orders to manage. This PR restores that feature to remove those links that are irrelevant to non-paying customers.

### How to test the changes in this Pull Request:

1. Sign up as a new reader without making any purchases and log into/verify with My Account.
2. Confirm that "Subscriptions", "Orders", and "Payment Methods" links are not shown ("Newsletters" is still shown if the Newsletters plugin is available, to allow the user to sign up for newsletters if desired):

Screenshot 2024-09-05 at 10 12 04 AM

3. Complete a donation or purchase and revisit My Account. Confirm that "Subscriptions", "Orders", and "Payment Methods" links are now shown, and that "Account Details" and "Subscriptions" links are the first two items in the menu.

Screenshot 2024-09-05 at 10 19 32 AM

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by ronchambers** [comment]
Hi @dkoo - I took at look at this (via Claudiu) and here is my review:

I attempted to complete all the Reader Activation steps (mailchimp, captcha, etc) in my local dev, but decided to just do my testing using `define( 'IS_TEST_ENV', true )`  Once that was added to my config, I refreshed a test user's my-account page and the menu matched what you shared in the first screenshot above.  This makes sense due to the `if ( Reader_Activation::is_enabled() )` check.

I then did different types of purchases: one time (with/without saving payment info), monthly subscription, and a download.  In each case, the correct menu items showed up based on the data the code checks for (subscriptions, orders + payment methods, addresses (when fields existed), and downloads).  

The menu ordering matched your screenshots too.

(Unrelated to this PR's code: I also confirmed the Newsletters link will go away if Newspack Newsletters is deactivated.)

**Summary: reviewed + tested = PASS.**

**Comment by dkoo** [comment]
Thank you, @ronchambers! Are you able to give the PR an "Approved" review?

**Review by ronchambers — APPROVED** [review]
Approved.  (Please see [comment](https://github.com/Automattic/newspack-plugin/pull/3394#issuecomment-2347438399) above)

**Comment by ronchambers** [comment]
@dkoo - If you want me to merge, let me know.

**Comment by dkoo** [comment]
Thanks, @ronchambers! Merging now.

**Pull request merged**
