### PR TITLE
Update header and footer style

### PR DESCRIPTION
**Pull request by thomasguillot**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR updates the header and footer to look more like Gutenberg. Making it a little bit more compact. We also have a "Return to Dashboard" button (the N logo) which we didn't use to have.

__After__
after

__Before__
before

### How to test the changes in this Pull Request:

1. Switch to this branch
2. Check all the different wizards, including the set up.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Review by miguelpeixe — CHANGES_REQUESTED** [review]
Loving the minimalism!

I noticed that the new design deprecates `subHeaderText` from the wizard screen. If this is intended, I think we should also remove it throughout the existing wizards and make sure that we are not leaving behind any important wizard information.

**Comment by thomasguillot** [comment]
Thank you @miguelpeixe!

I fixed the Required Plugins screen in https://github.com/Automattic/newspack-plugin/pull/1161/commits/96af60ba81cc5d195d5f46f2f58d6f6ff73da62d

> I noticed that the new design deprecates `subHeaderText` from the wizard screen. 

It's not deprecated as such. I didn't want to remove `subHeaderText` everywhere in case we were going to re-use it in the future so I added a `screen-reader-text` class to it (https://github.com/Automattic/newspack-plugin/pull/1161/files#diff-ee508ddb54294bc6d8f45b0c9dad608a96c2eaebf0264e36efd0799e9f9b323dR81)

**Review by miguelpeixe — CHANGES_REQUESTED** [review]
Thank you for revising, @thomasguillot !

>  I didn't want to remove subHeaderText everywhere in case we were going to re-use it in the future so I added a screen-reader-text class to it

Good thinking! I agree that we might want to re-use the subheader eventually and it's great to keep it for accessibility.

Sorry for not noticing it earlier, but there's also this margin issue with the Notice component on the `withWizard` HOC:

image

**Comment by thomasguillot** [comment]
Well spotted, @miguelpeixe!

Fixed in https://github.com/Automattic/newspack-plugin/pull/1161/commits/14cb24443f8136aab419aebef6578e8c490e64c4

**Review by miguelpeixe — DISMISSED** [review]
Clean solution! Thank you for all the revisions 💯

**Comment by thomasguillot** [comment]
I need a new review. I had to fix some conflicts with `master`.

**Review by miguelpeixe — APPROVED** [review]

**Pull request merged**
