### PR TITLE
feat: jetpack default modules

### PR DESCRIPTION
**Pull request by jaredrethman**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/trunk/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Adds `jetpack_get_default_modules` hook for delegating Jetpack default active modules on install. 

### How to test the changes in this Pull Request:

1. Check out this branch.
2. Run `wp jetpack reset modules` and confirm with "yes".
3. Navigate to Jetpack modules admin page i.e. `/wp-admin/admin.php?page=jetpack_modules&activated=true`
4. Cross reference list of active modules matches the list on https://github.com/Automattic/newspack-plugin/blob/feat/jetpack-default-modules/includes/plugins/class-jetpack.php#L33

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Review by dkoo — CHANGES_REQUESTED** [review]
@jaredrethman this is a good start, and works as described in the testing instructions. But I'm not sure it goes quite far enough, since you have to run the `wp jetpack reset modules` CLI command for it to take effect. The way Atomic sites are configured, they come with Jetpack preinstalled, so the default modules hook may never get called for Newspack sites. At the very least, we should probably enable the default modules when a Newspack site is finished getting setup, right? 

To that end, there's an [option](https://github.com/Automattic/newspack-plugin/blob/trunk/includes/wizards/class-setup-wizard.php#L14) that gets updated when a Newspack site first gets setup. Maybe we can hook into this option value getting set to `true` and set the modules then. I would check whether this is enough to satisfy the Support team's original request. 

Beyond that, I'm getting a warning when I run the `wp jetpack reset modules` CLI command:

```
Warning: Trying to access array offset on value of type bool in /srv/htdocs/wp-content/plugins/jetpack/jetpack_vendor/automattic/jetpack-waf/src/class-brute-force-protection.php on line 1146
```

**Comment by jaredrethman** [comment]
> @jaredrethman this is a good start, and works as described in the testing instructions. But I'm not sure it goes quite far enough...

I misunderstood the request in the ticket, was using the filter suggested there.

> The way Atomic sites are configured, they come with Jetpack preinstalled, so the default modules hook may never get called for Newspack sites. At the very least, we should probably enable the default modules when a Newspack site is finished getting setup, right?

I'm trying to find information on this, are you able to confirm that Jetpack is installed + active at the start/end of setup?

> To that end, there's an [option](https://github.com/Automattic/newspack-plugin/blob/trunk/includes/wizards/class-setup-wizard.php#L14) that gets updated when a Newspack site first gets setup. Maybe we can hook into this option value getting set to `true` and set the modules then. I would check whether this is enough to satisfy the Support team's original request.

I'll proceed using the `update_option_{$option_name}` hook when `newspack_service_enabled` is set to `true`, does that sounds correct?

> Beyond that, I'm getting a warning when I run the `wp jetpack reset modules` CLI command:
> 
> ```
> Warning: Trying to access array offset on value of type bool in /srv/htdocs/wp-content/plugins/jetpack/jetpack_vendor/automattic/jetpack-waf/src/class-brute-force-protection.php on line 1146
> ```

I think this relates to your local setup, specifically your `host` see here - https://github.com/Automattic/jetpack-production/blob/trunk/jetpack_vendor/automattic/jetpack-waf/src/class-brute-force-protection.php#L1146, will confirm.

**Comment by jaredrethman** [comment]
@dkoo have adjusted (https://github.com/Automattic/newspack-plugin/pull/2959/commits/ce86bb3f96f5f42de07a0556cc45bc11025f8fbe) Jetpack default modules activation when:
* `newspack_setup_complete` option is added and value is set to `1`
* `newspack_setup_complete` option is set to `1` https://github.com/Automattic/newspack-plugin/blob/ce86bb3f96f5f42de07a0556cc45bc11025f8fbe/includes/wizards/class-setup-wizard.php#L227

**Review by dkoo — APPROVED** [review]
@jaredrethman this is working how I expect, now—when I install the Newspack plugin and complete setup, the default Jetpack modules are set automatically. Thanks for the changes!

**Comment by gamebits** [comment]
Thank you for completing this request! pamTN9-8n2-p2

**Pull request merged**
