### PR TITLE
feat(amp-plus): allow OneSignal script

### PR DESCRIPTION
**Pull request by adekbadek**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Alternate approach from #417 to handling push notifications. Instead of making them work within AMP constraints, using AMP Plus mode.

### How to test the changes in this Pull Request:

1. Deactivate the [PWA plugin](https://wordpress.org/plugins/pwa), if active (see https://github.com/Automattic/newspack-plugin/issues/2104)
1. Register and create a new app at [app.onesignal.com](https://app.onesignal.com) – be sure to choose "WordPress" as the integration in the setup wizard
2. Install [OneSignal WP plugin](https://wordpress.org/plugins/onesignal-free-web-push-notifications/) (`onesignal-free-web-push-notifications`) and configure it
3. Ensure AMP plugin is active and AMP Plus is enabled (`NEWSPACK_AMP_PLUS_ENABLED` environment variable is set to `true`)
4. Visit the homepage in a new (non-incognito!) session
5. Observe a notification bell icon appear in the lower right corner
6. Click it to subscribe to notifications
7. From the OneSignal dashboard, observe a new user has been added (in Audience -> Users)
8. Send a new notification, observe that it works 

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by yogeshbeniwal** [comment]
@adekbadek Looking forward for this 👍

**Comment by yogeshbeniwal** [comment]
@adekbadek This will a good feature to have if its still a priority for development.

**Comment by adekbadek** [comment]
We're discussing this internally – we'd like to implement this, but first establish a protocol for assessing performance impact of these added scripts.

**Comment by yogeshbeniwal** [comment]
@adekbadek PageSpeed Insights is a good way to track performance impact for all enhancement.

**Comment by adekbadek** [comment]
Blocked by https://github.com/OneSignal/OneSignal-WordPress-Plugin/pull/298

**Comment by rgomezp** [comment]
Howdy @adekbadek ,
298 is now merged and released. 

Cheers

**Comment by leogermani** [comment]
I tried to test it and went as far as seeing the Bell on the page.

When I click on it, a new blank browser windows shows up and closes very quickly, but nothing happens.

I got the same behavior both on desktop and mobile

Maybe I'm missing some configuration step?

**Comment by adekbadek** [comment]
Might be a setup error, make sure you have AMP Plus enabled and the latest version of the OneSignal plugin. 

I was able to set this up on a fresh site, but run into other issue: https://github.com/Automattic/newspack-plugin/issues/2104. To test this properly, PWA plugin has to be deactivated. I've updated the description.

**Review by leogermani — APPROVED** [review]
Tested again disabling PWA and it worked fine.

**Pull request merged**
