### PR TITLE
feat: update variation styles

### PR DESCRIPTION
**Pull request by laurelfulford**
### All Submissions:

* [ ] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/trunk/.github/CONTRIBUTING.md)?
* [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR, along with https://github.com/Automattic/newspack-blocks/pull/1729, makes some tweaks to the variation styles:

* It reorders the SCSS a bit (moving the variations to the bottom of the modal CSS)
* It adjusts the styles to account for mixed height variations, for products that include fees, and products that are on sale.

See: 1205234045751551-as-1206482127342706

### How to test the changes in this Pull Request:

1. Apply this PR and https://github.com/Automattic/newspack-blocks/pull/1729, and run `npm run build` for both plugins.
2. Create two products with variations: one with a regular variable product, and one with variable subscriptions.
3. Of the variations, try adding some different price configurations: for either, add a sales price to at least one product, and for the subscription product, add an initial fee and a trial.
4. Assign each of those products to a checkout button block.
5. Do a visual review of the front-end and confirm things look okay -- primarily the additional info (sale price, fees)

image

image

6. As an edge case, you can try to make one variation taller (usually by having a really long variation name, or two + variations applied) and confirm that the visual treatment of the taller variation makes sense: 

image

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by laurelfulford** [comment]
Copying over some good feedback from @thomasguillot:

> At first glance, it looks okay. My only suggestion would be to align the prices horizontally.

image

image

**Comment by laurelfulford** [comment]
@thomasguillot do you think it would work to add more space around the price always to create space for the sale price? Or is this too much of a change for something that won't be on most sites?

image

**Review by dkoo — APPROVED** [review]
"...and a $80 sign-up fee" sounds funny, but looks like that's not from our template: https://github.com/Automattic/woocommerce-subscriptions-core/blob/trunk/includes/class-wc-subscriptions-product.php#L400

Otherwise looks great!

Screenshot 2024-05-15 at 4 43 01 PM

**Comment by laurelfulford** [comment]
Thanks @dkoo! 

> "...and a $80 sign-up fee" sounds funny...

It should be **an** $80 fee 😆 Seriously though, it is a little strange in this context -- possibly something we can experiment with filtering down the road?

**Comment by dkoo** [comment]
Seems like it'd be a rare edge case for us. I'm not even sure there's been a Newspack publisher who charges signup fees? Probably best fixed in the source repo, anyway...

**Comment by thomasguillot** [comment]
@laurelfulford I pushed some minor changes: https://github.com/Automattic/newspack-plugin/pull/3107/commits/66e3548814bc7555786b81b9983d656fcfb7e583
(I messed up the commit message. It's not just a fix for the line-height)
One thing I noticed is we were using the wrong colour (`#111111` vs `#1e1e1e`) so this should be fixed now.
I also tweaked the spacings a little bit.

**Comment by laurelfulford** [comment]
Thanks @thomasguillot! 

The changes look good -- the only thing I tweaked was removing the `color: red` [here](https://github.com/Automattic/newspack-plugin/commit/66e3548814bc7555786b81b9983d656fcfb7e583#diff-c7bef86c40e15929c368d329daf3c59dcedd05ef4ec7bc5b69e73465b45bf3f9R129) -- that looks like a test line to make sure that everything else was inheriting correctly.

I'm going to go ahead and merge this one!

**Pull request merged**
