### PR TITLE
feat(reg-block): add loading message while registration is processing

### PR DESCRIPTION
**Pull request by chickenn00dle**
### All Submissions:

* [ ] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/trunk/.github/CONTRIBUTING.md)?
* [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes [0/1200550061930446/1206650276976874](https://app.asana.com/0/1200550061930446/1206650276976874/f).

This PR adds a "loading" message while the registration block is processing. This is because the block does a lot behind the scenes and can take a good amount of time to complete registration. It must:

- Send a captcha request
- Create a new user account
- If the registration block is set to add ESP contacts, add a new contact

This is similar to https://github.com/Automattic/newspack-newsletters/pull/1456, however we can't optimistically succeed here since in the case of content gates, we need to verify a user has been created before we move on.

So this PR adds a simple loading message while the form processes to reassure users that the gears are still turning.

Screenshot 2024-03-15 at 17 18 18

### How to test the changes in this Pull Request:

1. On a test site, set up a registration wall content gate: https://help.newspack.com/engagement/reader-activation-system/content-gating/#getting-started
2. Activate the memberships plugin and create a membership plan for all new registrations, restricting all posts to members of this plan
3. Visit any post on your site as a logged out user and scroll until the registration wall triggers
4. Enter a valid email address and verify a message appears at the bottom indicating the process may take a few seconds

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Review by adekbadek — CHANGES_REQUESTED** [review]
Works as described, but the new message is almost imperceptible, it's so small and pushed to the bottom of the UI. @Automattic/newspack-design could you please weigh in here?

image

**Comment by chickenn00dle** [comment]
> but the new message is almost imperceptible, it's so small and pushed to the bottom of the UI. 

Good point. Do we have a universal "loading" component to fall back to for cases like this? That might be a good alternative.

In any case, I'll wait to hear what design might have to say about this one!

**Comment by thomasguillot** [comment]
Can we change the "Sign up" button to include a spinner, while maintaining the original width?

(Spinner e.g. https://codepen.io/thomasa8c/pen/yLjKqvW)

**Comment by thomasguillot** [comment]
FWIW this will become a recurring pattern in My Account

Screenshot 2024-04-05 at 22 21 31

**Comment by chickenn00dle** [comment]
Closing in favor of https://github.com/Automattic/newspack-plugin/pull/3180

**Pull request closed without merging**
