### PR TITLE
fix(woocommerce): fix order-pay page when using woocommerce-membershi…

### PR DESCRIPTION
**Pull request by adekbadek**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes an issue with the `woocommerce-memberships-for-teams` plugin when attempting to complete a pending-payment order. 

See 1200550061930446-as-1206314181096660

### How to test the changes in this Pull Request:

1. Activate `woocommerce-memberships-for-teams` on top of regular Newspack & Woo setup
2. Edit the monthly donation product and tick "Team membership" checkbox:

image

3. Create a membership plan with access based on buying a recurring donation product
1. Make a monthly donation as a new user, then as admin manually update the order status to "Pending payment"
1. Visit the "Customer payment page" (when logged in as the customer)
4. On `release` -> observe the cart is emptied and you cannot pay for the order
6. Switch to this branch, visit the payment page link again, observe a regular Woo cart experience*

\* you won't be able to actually pay because of the manual setting of 'pending payment' status

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Review by chickenn00dle — COMMENTED** [review]
I am not able to reproduce the issue on `release` branch locally.

Here is a pending order for my monthly donation product:
Screenshot 2024-02-14 at 11 24 28

And the associated membership:
Screenshot 2024-02-14 at 11 25 19

And finally when I open the `Customer payment page` link while logged in as the customer, I am redirected to checkout with no errors:
Screenshot 2024-02-14 at 11 27 02

Is there a missing step to reproduce?

**Comment by adekbadek** [comment]
> Is there a missing step to reproduce?

Yes! Sorry for that. I've updated the description (added step 2).

**Review by chickenn00dle — APPROVED** [review]
Great! Thanks @adekbadek 🙌 

I'm able to reproduce now and can confirm the fix. I'm gonna go ahead and approve since there is a publisher waiting for it, but I'm wondering if this should be submitted as a fix in the memberships for teams repo? At least it seems like the issue is self contained within that plugin.

**Comment by adekbadek** [comment]
It's closed-source, might be worth reaching out via some channel though.

**Pull request merged**
