### PR TITLE
Chore / IA Refactor Admin Tabs to Header

### PR DESCRIPTION
**Pull request by ronchambers**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/trunk/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Refactored trait `Admin_Tabs` to `Admin_Header` so that the header can be used without requiring tabs.  Also refactored the only file that was using this code ("Advertising > Sponsors") to use the new code.  (The pure React pages seem to use a different header completely).

### How to test the changes in this Pull Request:

1.  Pull this branch on top of the `epic/ia` branch.
2.  In your browser, load WP Admin > Advertising > Sponsors page.
3.  Verify the header with tabs displays correctly with `margin-left: -20px` too.  (Attached)

pr-admin-header-1

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by ronchambers** [comment]
Hi @jaredrethman I'll tag you as a reviewer and reach out in Slack too.  I'm still getting back into doing React, so if I did something incorrect please let me know :-)  

I tried to move files

```
src/wizards/wizards-admin-header.tsx
src/wizards/wizards-admin-header.scss
```

into their a new folder at `src/wizards/admin-header/` to organize things a bit better, but I was having issues with `webpack.config.js` so I left them where they are.  If that is an issue, please let me know and I'll try to move them again.

Thanks!

**Review by jaredrethman — APPROVED** [review]
@ronchambers nice work! Approved 👍

**Review by dkoo — DISMISSED** [review]
@ronchambers nice work on this! 

> I tried to move files into their a new folder at `src/wizards/admin-header/` to organize things a bit better, but I was having issues with `webpack.config.js` so I left them where they are.

If you want to move them to a subdirectory then this would work: https://github.com/Automattic/newspack-plugin/compare/chore/ia-refactor-header-tabs...chore/ia-refactor-header-tabs--edit?expand=1

Otherwise I'm okay with leaving them where they are. Up to you!

I have one other bit of feedback which doesn't originate with this PR, but which is illustrated very nicely in your PR description. Is it possible to give these inline nag notices 25px of bottom margin when they appear above our header components? I think this would apply for both the standalone admin header app and the regular wizard app.

Screenshot 2024-09-18 at 4 32 21 PM

**Comment by jaredrethman** [comment]
> I have one other bit of feedback which doesn't originate with this PR, but which is illustrated very nicely in your PR description. Is it possible to give these inline nag notices 25px of bottom margin when they appear above our header components? I think this would apply for both the standalone admin header app and the regular wizard app.
> 
> Screenshot 2024-09-18 at 4 32 21 PM

@dkoo thought it worth mentioning, admin notices are removed from current wizards:
https://github.com/Automattic/newspack-plugin/blob/4a35190630626bb3711d1c85c75d5c6cd91bb6f2/includes/class-newspack.php#L262-L274

**Comment by dkoo** [comment]
Got it! So we'd only need to handle in the admin-header screens, then (or hide the notices there, too).

**Comment by ronchambers** [comment]
@dkoo / @jaredrethman  - I separated the nag/notification request into it's own Asana task in the IA project.  I tagged you both on it, but no assignee/due date yet.  

In regards to this PR, I retested everything after the "edit" sub-branch was merged in.  All is good.  Please merge when you can.  Thanks!

**Pull request merged**
