### PR TITLE
feat(donations-stripe): integrate w/ woocommerce-memberships

### PR DESCRIPTION
**Pull request by adekbadek**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Adds integration with `woocommerce-memberships` plugin.

### How to test the changes in this Pull Request:

1. Switch to `add/handle-wc-memberships` branch of `newspack-blocks` plugin (https://github.com/Automattic/newspack-blocks/pull/1096)
2. Follow the setup from https://github.com/Automattic/newspack-plugin/pull/1593 (steps 1-3)
3. Activate `woocommerce-memberships` plugin and set up a membership plan* tied to donations
4. In a session as a non-logged-in visitor, confirm the content is restricted (as per membership plan) and make a donation
5. Observe the restricted content is now visible
6. Observe that a user account was created and you're now logged in by visiting `/wp-admin` page
7. In a different session, make a donation as an already logged-on user. Observe the restricted content is now visible as per plan

\* e.g. restrict all post content unless one of the Newspack Donations products was bought

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Review by miguelpeixe — CHANGES_REQUESTED** [review]
Not sure exactly why, but after the succesful purchase, the user account is created and authenticated but the order is not set to the customer ID and the user doesn't get access to the membership. Accessing `/my-account/orders/` I get `No order has been made yet.` and the same to `/my-account/members-area/`.

This is the membership plan config:

image

Don't know if related but with debug mode I get several warnings regarding deprecated usage of `is_offline()` and `is_500()` from the Membership plugin:

````
PHP Notice:  is_offline was called <strong>incorrectly</strong>. Conditional query tags do not work before the query is run. Before then, they always return false.
````

```
PHP Notice:  is_500 was called <strong>incorrectly</strong>. Conditional query tags do not work before the query is run. Before then, they always return false.
```

**Comment by adekbadek** [comment]
@miguelpeixe can you confirm if the site is publicly available, so webhook endpoint can process Stripe request?

> Don't know if related but with debug mode I get several warnings regarding deprecated usage of is_offline() and is_500() from the Membership plugin:

Are you sure these are coming from WC Memberships? I can't see any use of these functions in the plugin code.

**Comment by miguelpeixe** [comment]
> Are you sure these are coming from WC Memberships? I can't see any use of these functions in the plugin code.

The stack trace points to it:

image

It's mostly a deprecation warning that we probably shouldn't have to worry right now.

**Comment by miguelpeixe** [comment]
> Are you sure these are coming from WC Memberships? I can't see any use of these functions in the plugin code.

The stack trace points to it:

image

It's mostly a deprecation warning that we probably shouldn't have to worry right now.

**Review by miguelpeixe — APPROVED** [review]

**Pull request merged**
