### PR TITLE
feat(popups wizard): add archive page permalink as preview URL

### PR DESCRIPTION
**Pull request by kariae**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Enable previewing campaign prompts on an archive page. This is needed to [preview the new inline prompts placement inside the archive pages](https://github.com/Automattic/newspack-popups/pull/621).

### How to test the changes in this Pull Request:

1. If it's not released, please checkout #plugin PR
2. Pull this PR, and add a new `inline` prompt from the campaign menu (you need the newspack-campaign plugin to be active).
3. In the `placement` option select `In archive pages`.
4. Preview the new prompt from the prompt list and observe that it loads on a category archive page.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Review by adekbadek — CHANGES_REQUESTED** [review]
The Campaigns wizard integration is missing two features:

1. The new placement handled in the prompt settings modal:

image

2. The new placement handled in the new prompt modal:

image

**Comment by kariae** [comment]
Good catch, thanks! I add this. (sorry by the way for the prompt/popups inter-change in the commit message 😅 )

**Comment by kariae** [comment]
maybe worth having an icon too, @thomasguillot if you can help with this one, please 🙇

**Comment by thomasguillot** [comment]
> The new placement handled in the new prompt modal:

Do we really need to add this to the new prompt modal? Surely it's just a slightly more specific "inline" prompt?
I'm worried that adding a new option here will break the grid/layout of the modal and will just look odd.

**Comment by kariae** [comment]
The updated look for reference:
Screen Shot 2021-09-20 at 1 55 27 PM

**Comment by thomasguillot** [comment]
I am concerned about the `Grid` being uneven. That being said, I understand discoverability of features is more important. I see a few solutions here:

1. Add this new option and the "Manual Only" option (it's currently missing), making the grid less uneven.
Screenshot 2021-10-18 at 14 02 06

2. Remove the grid completely and have the options in small on top of each other, inside a narrow `Modal`.
Screenshot 2021-10-18 at 14 10 33

3. Switch the grid to 2 columns (and "Manual Only" could still be added) and change to the default `Modal` width.
Screenshot 2021-10-18 at 14 13 38

_1 would probably be my preferred solution_

**Pull request merged**
