### PR TITLE
Install The Newspack Theme

### PR DESCRIPTION
**Pull request by jeffersonrabb**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR adds the Newspack Theme to the list of plugins and takes care of handling it as an unusual case. The theme is installed as part of the Setup Wizard. The PR also includes a stub of a configuration manager for the theme, which at present only sets the colors to be default (which is  the theme default anyway). This configuration manager will eventually be the main interface between the Site  Design wizard and the Theme. The PR also contains some minor UI/text changes to the Setup Wizard to indicate that the theme is being installed as well as plugins.

### How to test the changes in this Pull Request:

1. Check out this branch, run `npm run build:webpack`
2. Deactivate and delete the theme.
3. Run through the Setup Wizard. 
4. Verify that the theme has been installed and is the active theme. 

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by jeffersonrabb** [comment]
When the Newspack theme is initially installed the API returns status of `uninstalled`. A page refresh corrects this, but this glitch throws off the Setup Wizard, which won't complete. This does not occur if the theme is installed but inactive—it happens only if the theme is being installed and activated. 

The problem seems to lie in https://github.com/Automattic/newspack-plugin/pull/249/files#diff-044b9390f497ea129e19496244893c6eR191, where `wp_get_theme()` returns false immediately after https://github.com/Automattic/newspack-plugin/blob/2ff253f84882fa6782f6d12fbd114017c33861fa/includes/util.php#L42-L78 has been executed. This can be verified by following these steps:

- Add `error_log( 'Current theme URI: ' . $plugin_uri );` immediately below this line https://github.com/Automattic/newspack-plugin/blob/2ff253f84882fa6782f6d12fbd114017c33861fa/includes/class-plugin-manager.php#L192
- `tail` the PHP error log. 
- Delete the Newspack theme.
- Run the Setup wizard and observe the log.

**Comment by claudiulodro** [comment]
I've simplified the check so that it doesn't require the theme to be fully initialized and loaded to work (it just checks the active stylesheet): https://github.com/Automattic/newspack-plugin/pull/249/commits/6b1f25b838a254cab8c67c8064a900eb6901f0be

This has solved the issue in my testing.

**Comment by jeffersonrabb** [comment]
After running the Setup Wizard I'm sometimes seeing two instances of the Newspack theme in the themes admin. There will be two folders in the theme directory, one with the correct name (`newspack-theme`) and one with a string appended (`newspack-theme-iov549`).  Also see this PHP warning in the log:

`PHP Warning:  rename(/srv/www/wordpress-simple/public_html/wp-content/themes/newspack-theme-iov549,/srv/www/wordpress-simple/public_html/wp-content/themes/newspack-theme): File exists in /srv/www/newspack-repos/newspack-plugin/includes/util.php on line 68`

**Comment by jeffersonrabb** [comment]
Looking a bit deeper, these problems stem from a few React problems with the Setup Wizard. The key is the handling of the `hidden` prop in `withWizardScreen`:

https://github.com/Automattic/newspack-plugin/blob/master/assets/components/src/with-wizard-screen/index.js#L39-L45

If `hidden` changes during the lifecycle of the wizard, the content will be re-rendered. In the Setup wizard this means that if the 4th screen is reached before all plugin installation is complete, `PluginInstaller` will be re-mounted. This causes a second API request to be made. The failed & double theme installations occur because two request are in flight at the same time which is likely to bork just about any plugin or theme installation—one will fail since the directory already exists. This creates a race condition, which explains the difficulty we've had reliably reproducing  this issue. 

Since it's unrelated to the work in this PR I'm going to merge, and will open a new PR with fixes for the Setup wizard. 

Likely related to https://github.com/Automattic/newspack-plugin/issues/188, possibly https://github.com/Automattic/newspack-plugin/issues/97

**Pull request merged**
