### PR TITLE
fix: alpha fixes

### PR DESCRIPTION
**Pull request by dkoo**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes some issues resulting from a bad hotfix merge.

### How to test the changes in this Pull Request:

1. Follow testing instructions in #2820 and make sure they work
2. Follow testing instructions in #2733 and make sure they work
3. Re: [this comment](https://github.com/Automattic/newspack-plugin/pull/2835#pullrequestreview-1805563860), enable some but not all billing address fields in **Newspack > Reader Revenue > Donations**. 
4. Complete a purchase of a shippable product, then log into/verify My Account, then visit Addresses.
5. Confirm that when editing the **billing** address, only the fields enabled in Reader Revenue in step 3 are required, and that you can save with empty "optional" fields (but not with empty "required" fields).
6. Confirm that when editing the **shipping** address, all default address fields are still required.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Review by adekbadek — APPROVED** [review]
1. Address editing: I've just enabled two address fields for the checkout flow, but in the edit view all are displayed and required. Not sure if that's expected, description in https://github.com/Automattic/newspack-plugin/pull/2733 does not mention such a case. 
2. I was not able to test https://github.com/Automattic/newspack-plugin/pull/2820 successfully, but that's the case also on `master`, and I do see that this change here reinstates code mistakenly removed in f5bc0307b8ab0f7f62167f58c1efe6f4a4a97763.

**Comment by dkoo** [comment]
> Address editing: I've just enabled two address fields for the checkout flow, but in the edit view all are displayed and required. Not sure if that's expected, description in https://github.com/Automattic/newspack-plugin/pull/2733 does not mention such a case.

Hmm, we're not filtering the billing fields shown here to match them up with the fields selected in Reader Revenue. Do you think that's a requirement?

**Comment by dkoo** [comment]
@adekbadek 20cbded filters the address fields for the "edit billing address" page only, so that only fields enabled in Reader Revenue > Donations are required. Other address fields are still shown but are marked optional. Updated testing instructions, too.

**Comment by adekbadek** [comment]
That works for address fields, but "Phone" is added later in WC. I've updated the filter used to make it filter the billing fields at a later stage, when all are added (f0b5490d9003f230f0a0b350e0cebf733f44ed30).

**Review by adekbadek — APPROVED** [review]

**Pull request merged**
