### PR TITLE
feat/connections view

### LINKED ISSUE #984: "Connections" view
https://github.com/Automattic/newspack-plugin/pull/962 introduces Google connection, on top of connection to WPCOM. There should be a separate view to manage those. User should be able to:

- Connect their Google & WPCOM accounts 
- Revoke the connections
- Google is dependent on WPCOM, the UI should reflect that

### PR DESCRIPTION
**Pull request by adekbadek**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Adds a new wizard, called Connections, for managing all third-party authorisations.

@thomasguillot - as per [your suggestion](https://github.com/Automattic/newspack-plugin/issues/984#issuecomment-862321456), this is kept similar to the Integrations step of Setup flow:

image

Closes #984

### How to test the changes in this Pull Request:

1. On a fresh site, load the Newspack dashboard. Observe there's no "Connections" wizard available
2. Add the `NEWSPACK_WPCOM_CLIENT_ID` environment variable
3. Observe the Connections wizard is now available, and it allows the user to connect the site to WordPress.com
4. Add the `NEWSPACK_GOOGLE_OAUTH_PROXY` environment variable (see #1122 for more details)
5. Observe an additional connection option - Google
6. Observe that the Google option is disabled, with information that first WordPress.com should be connected
7. Authorise WordPress.com
8. Observe that now Google can be authorised - do it
9. Revoke permissions of both, observe the authorisation flow can be followed again

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by thomasguillot** [comment]
Brilliant!

**Review by miguelpeixe — CHANGES_REQUESTED** [review]
I was not able to connect to Google even though I had the WordPress.com connection and the proper `NEWSPACK_GOOGLE_OAUTH_PROXY` defined. I tried with a local setup and a newly configured Newspack site using JN.

After attempting to connect, the API response to the `/oauth/google` endpoint remained `{"success":false}` without any further information and the screen stuck on loading:

image

Disconnecting from WordPress.com redirects to the dashboard homepage, is this intended? I expected to stay on the Connections view.
 
I also wonder if we can add the WordPress.com and Google connections to the "Integrations" onboarding step and also bring those connections to this view? Unify the connections/integrations component would also be better to maintain.

**Comment by adekbadek** [comment]
Should be fixed now! The issue was with WPCOM token encoding.

> Disconnecting from WordPress.com redirects to the dashboard homepage, is this intended? I expected to stay on the Connections view.

Good idea, changed in 64c2953a4002e04c8581f057d959c4568e1aba38

> I also wonder if we can add the WordPress.com and Google connections to the "Integrations" onboarding step and also bring those connections to this view? Unify the connections/integrations component would also be better to maintain.

Good idea too, but I'd prefer to tackle that in a separate PR to unblock other things with this PR.

**Review by miguelpeixe — APPROVED** [review]
Thank you for revising, it is working as expected also with the support constants not present.

One last non-blocking suggestion, as part of the OAuth flow we are redirected to a page with the `csrf_token` and `access_token` parameters for validation/registration. While on this page we are presented with an incorrect state of the application. Would be best if presented with some sort of "Authorizing..." message to represent the temporary aspect of this screen.

**Comment by adekbadek** [comment]
> While on this page we are presented with an incorrect state of the application. Would be best if presented with some sort of "Authorizing..." message to represent the temporary aspect of this screen.

There's a [waiting animation in this flow](https://github.com/Automattic/newspack-plugin/blob/493772a2cbb47f7e1b63903b982f36a97952986b/assets/wizards/connections/views/main/index.js#L24), but the with all the redirects it's not so smooth. I agree this could be improved, but it's not super-important.

**Pull request merged**
