### PR TITLE
feat: popover to choose type of new campaign

### PR DESCRIPTION
**Pull request by jeffersonrabb**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Test along with Automattic/newspack-popups#374.

This PR adds a Popover to the "Add New" button that lets users pick which type of Campaign they want to create.

Closes https://github.com/Automattic/newspack-plugin/issues/790

### How to test the changes in this Pull Request:

1. Navigate to Campaigns
2. Click on the "Add New" button
3. Create every type of Campaign possible and check if it passed the correct settings in the editor

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by jeffersonrabb** [comment]
@thomasguillot this is functional but needs design work. The placement of the `Popover` causes the `Button` to reposition when open, plus I'm sure you'll want to change the appearance of the links. Test along with https://github.com/Automattic/newspack-popups/pull/374.

**Comment by thomasguillot** [comment]
> @thomasguillot this is functional but needs design work. The placement of the `Popover` causes the `Button` to reposition when open, plus I'm sure you'll want to change the appearance of the links. Test along with [Automattic/newspack-popups#374](https://github.com/Automattic/newspack-popups/pull/374).

@jeffersonrabb Done. Thank you very much.

**Comment by thomasguillot** [comment]
Waiting for https://github.com/Automattic/newspack-plugin/pull/794 to be merged first since it brings some visual changes to the Popover.

I will then need to slightly change the CSS in this PR.

**Review by adekbadek — APPROVED** [review]
All good, but first https://github.com/Automattic/newspack-popups/pull/374 needs to be merged.

**Comment by jeffersonrabb** [comment]
> All good, but first [Automattic/newspack-popups#374](https://github.com/Automattic/newspack-popups/pull/374) needs to be merged.

My mistake for leaving that in draft status (and with failing tests). It's ready for review now.

**Pull request merged**
