### PR TITLE
Add tickets list in Support wizard

### PR DESCRIPTION
**Pull request by adekbadek**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Add a tickets list view to the Support wizard.

image

### How to test the changes in this Pull Request:

1. Set up a [WPCOM app for OAuth](https://developer.wordpress.com/apps)
2. Ensure support-related env variables are present (as per README.md)
3. Visit the Support wizard in the Newspack plugin
4. Authenticate, if necessary, with a WPCOM account 
5. Observe a list of open and closed tickets tickets, or a message informing about no tickets

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by adekbadek** [comment]
Sorry for that, some errors were not handled. Should be fixed by a9caf46169a180bbdd447be5e64dc12c510ee6b8

**Comment by philipjohn** [comment]
The tickets this pulls in are based on the current user. Will it only retrieve tickets where the current user is the requester? Or will it also include any tickets the user is CC'd on?

I ask because I can see multiple people from the same publishers wanting to see all the tickets. That makes authentication more difficult, unless we can include all CC'd tickets too.

**Comment by adekbadek** [comment]
> I now get the same error but on a different line:

@philipjohn I've added error handling there in 7becbb2911cbb54c2cee1bbace3caefc81df86d9 – you should now see the error in the frontend. What does it say?

> Will it only retrieve tickets where the current user is the requester? 

Exactly. But I'll explore the possibility of adding an "enhanced support history" or something endpoint to WPCOM.

**Comment by philipjohn** [comment]
Okay, that's working now, but I don't see my tickets. I just have the "no open tickets found". The test ticket I created was initially set to "New" which makes sense, so I escalated it to Newspack and saved it as "Open" but it still doesn't show in my tickets view.

The email address on the ticket is admin@local.test which matches the user account I'm logged in with, and I have chat authenticated successfully (but I supposed that's connected to my a8c email).

**Comment by adekbadek** [comment]
Yeah, you should change that WP user email. The ticket is submitted as the current user email, but tickets are retrieved as the WPCOM authenticated user.

**Comment by jeffersonrabb** [comment]
The no tickets state has an errant "0" in it:

Screen Shot 2020-05-19 at 6 23 57 AM

**Comment by jeffersonrabb** [comment]
A few notes on the ticket display:

- Can we show the total number of replies, and the date of the most recent one?
- If user action is required, can that be flagged? Possibly brought to the top?
- Can the ticket name be a link to the ticket in Zendesk?
- Show the ticket status? If the only options are `New`, `Open`, and `Closed` then the handling of Closed tickets already covers this, but if there are more status options it might be good to display.
- Is it possible to show an Excerpt, or Description of the ticket?
- Following on @philipjohn's comment about showing all tickets associated with the site, we would want to list the user who filed it.
- For a later iteration, search functionality would be great. Once we start using Zendesk for pre-launch tasks, the list could quickly become overwhelming, and a search feature could make it manageable.
- Also for later, we may need pagination.

**Comment by adekbadek** [comment]
@jeffersonrabb 

> The no tickets state has an errant "0" in it:

That should be fixed in 128fb754a72b6f5ca872cc7a44cef545116e088e

> A few notes on the ticket display

The current implementation displays all data available from the WPCOM's `/support-history` endpoint. Changing that endpoint (or creating a new one) might take a while, so I'd propose to file those changes as an issue – WDYT?

**Comment by jeffersonrabb** [comment]
> Changing that endpoint (or creating a new one) might take a while, so I'd propose to file those changes as an issue – WDYT?

Absolutely. Let's get this PR done as-is and address the rest later. Could you add the changes from https://github.com/Automattic/newspack-plugin/pull/520 into this PR? It's difficult to test the new HOC without token invalidation working.

**Comment by adekbadek** [comment]
>  Could you add the changes from #520

Done in f323038282b3d363ae9ec06b26d682307336a090

**Comment by adekbadek** [comment]
@jeffersonrabb I've opened #537 with your suggestions, besides this one:

> Can the ticket name be a link to the ticket in Zendesk?

The customer does not have access to Zendesk, so that would not be very useful. Or am I missing something?

**Comment by jeffersonrabb** [comment]
> The customer does not have access to Zendesk, so that would not be very useful. Or am I missing something?

No you're right. In testing this PR I received confirmation emails from Zendesk which included links to the tickets. I missed that these are in the links only because I'm an agent, which makes perfect sense.

**Comment by adekbadek** [comment]
> Something from #520 didn't make it through — after mangling the key or disconnecting the WP.com app I get this, with no option to reconnect

Thanks for catching that! Fixed in 4dde4c10ad39b82b8a418bc1fe0286eec3402d22

> the Chat screen throws a large number of this JS error

It will throw this error if you change wizard tab after initializing chat. This is a bug in `happychat-client` – it does not clean up event listeners after closing :/

**Comment by adekbadek** [comment]
@philipjohn having realised that WPCOM API does return the Zendesk status, I've updated the UI to show "Action required" tickets separately in 73c8e647b47c6d3e596b2a29033d221374da15d1

image

**Comment by philipjohn** [comment]
> The ticket is submitted as the current user email, but tickets are retrieved as the WPCOM authenticated user.

I'm still not able to see my tickets. Here's what I did:

1. On my local test site, newspack.test I logged in as admin (email admin@local.test)
1. Created a ticket
1. Checked the ticket was open (it's no. 3010865)
1. Checked the ticket view - no tickets
1. Changed the user account email address to the one associated with my WP.com account (`philipjohna8c`)
1. Refreshed the ticket view - no tickets
1. Changed the requester on the ticket to my A8c email address to exactly match both my local WP user account and the WP.com user account
1. Refreshed the ticket view - no tickets

I'm worried that if there is a mismatch between the WP user account email and the WP.com account email folks aren't going to see their tickets, and I know for sure that there is inconsistency with some publishers.

**Comment by adekbadek** [comment]
Got it. I've changed it so that the authenticated WPCOM user is used as the ticket requester in 22119089d1c1edc15a7de696d5bc671f93295e9b

**Pull request merged**
