### PR TITLE
Fine-tune and update dashboard/checklist options

### PR DESCRIPTION
**Pull request by claudiulodro**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR brings the dashboard in line with the latest designs (except images). All the checklists are present, but the ones that haven't been built yet are disabled. I've removed the demo checklist, since it's not needed now that we have a real checklist available.

### How to test the changes in this Pull Request:

1. `npm run clean; npm run build:webpack`
2. Navigate to the Newspack Dashboard. You should see this:
localhost_wp-admin_admin php_page=newspack
3. You should be able to go to the Reader Revenue checklist and not the other checklists.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by jeffersonrabb** [comment]
Let's keep this one open for a minute for two reasons:

1) @sonjaleix is close to done with the graphics so we can slot them in.
2) When the `<NewspackLogo>` PR ships (https://github.com/Automattic/newspack-plugin/pull/127) we can use that at the top of the dashboard to avoid duplication.

**Comment by claudiulodro** [comment]
I've updated this to use the `NewspackLogo` component in https://github.com/Automattic/newspack-plugin/pull/122/commits/88ca934ee7c5eedcb8ac5bfb79998ecec92191f6

**Comment by jeffersonrabb** [comment]
> I've updated this to use the `NewspackLogo` component in [88ca934](https://github.com/Automattic/newspack-plugin/commit/88ca934ee7c5eedcb8ac5bfb79998ecec92191f6)

It's nice that passing the component in as `headerText` works - very elegant!

**Comment by sonjaleix** [comment]
This is looking great and is beautifully responsive!

I've added the updated dashboard graphics in Figma
Screenshot 2019-06-27 13 12 44

One thing I've noticed: When clicking on a dashboard tile, the active state has a blue outline, see screenshot:
Screenshot 2019-06-27 13 13 21

**Comment by claudiulodro** [comment]
I've made the following changes:
- Added icons using the new icon designs.
- Fixed the blue outline issue when clicking on the cards.
- Brought everything up-to-date with master. You should be able to access the Reader Revenue and Advertising checklists through the dashboard now.

I believe this should be good to merge now. I'll give it a merge on Monday if nobody has any additional feedback.

**Pull request merged**
