### PR TITLE
fix(auth): check for otp hash cookie when processing auth request

### PR DESCRIPTION
**Pull request by chickenn00dle**
### All Submissions:

* [ ] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/trunk/.github/CONTRIBUTING.md)?
* [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes https://app.asana.com/0/1207817176293825/1208730419008823

This PR fixes an issue where its possible for readers to have otp token meta stored, but no otp hash cookie present which leads to the auth form getting stuck at the signin step.

### How to test the changes in this Pull Request:

1. As a reader, in an incognito window, open the auth modal via the sign in button
2. Enter the reader email to trigger sending an OTP code (but dont enter it)
3. Close the incognito window
4. Open a new incognito and try to login with the same email again. On `epic` the form will be stuck. On this branch it will not.

Note: On step 4, the auth modal will give you a warning to wait a minute before requesting another code if opened within a minute of the first window. This is expected. Its very unlikely readers will run into this particular issue within the otp timer minute window, but if we'd like to account for this as well, let me know!

Screenshot 2024-11-19 at 10 13 26

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Review by miguelpeixe — APPROVED** [review]

**Review by leogermani — APPROVED** [review]
Fixes the issue.

If I use a different email when I reopen the incognito window, I also get the "wait 1 minute" message... not sure if this should be expected, but not a big issue

**Comment by miguelpeixe** [comment]
> If I use a different email when I reopen the incognito window, I also get the "wait 1 minute" message... not sure if this should be expected, but not a big issue

That's weird. If that's a new session and a different user account, it shouldn't do that. Unless this other account also requested an OTP less than a minute ago.

**Comment by chickenn00dle** [comment]
Thanks y'all! Gonna merge for now to resolve the main issue. We can dig further into this 1 minute warning for other email issue in a follow-up PR if it ends up being a thing. I suspect readers will likely not run into this issue, but I guess we never know!

**Comment by chickenn00dle** [comment]
> If I use a different email when I reopen the incognito window, I also get the "wait 1 minute" message... not sure if this should be expected, but not a big issue

Also noting, I've tested this on my end and don't see this same issue @leogermani 


https://github.com/user-attachments/assets/7cbf17d9-af02-4350-884c-3d59b1b78c18

**Pull request merged**
