### PR TITLE
Wizard: (Re)add loading animation

### PR DESCRIPTION
**Pull request by thomasguillot**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

In order to get visual feedback when clicking a button, this PR adds back the loading animation.

### How to test the changes in this Pull Request:

Go to the advertising wizard. And toggle the different ads providers

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by jeffersonrabb** [comment]
What's the thinking behind the switch to a one-time animation vs. infinite as it was originally?

**Comment by thomasguillot** [comment]
> What's the thinking behind the switch to a one-time animation vs. infinite as it was originally?

@jeffersonrabb the original animation wasn't going from 0 to 100%. Instead it was doing a strange bouncing effect so it made sense to have in using `infinite`.

Now, it's a straightforward 0 to 100. And to me, it doesn't make sense to see the animation more than once since it should reach the 100 when it's fully loaded.

**Comment by jeffersonrabb** [comment]
> And to me, it doesn't make sense to see the animation more than once since it should reach the 100 when it's fully loaded.

I'm frequently seeing the animation complete long before the loading finishes, which leaves the UI grayed out with no animation. This is on a local development instance so of course it's unusually slow, but this could occur on production as well:

https://cloudup.com/cfq_5u4YZjW

**Comment by thomasguillot** [comment]
@jeffersonrabb In bdcccf9 I changed the animation to `infinite`. Is it any better?

**Pull request merged**
