### PR TITLE
feat(ras-acc): minor visual fixes

### PR DESCRIPTION
**Pull request by laurelfulford**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/trunk/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR, along with https://github.com/Automattic/newspack-blocks/pull/1747, fix a handful of spacing and sizing issues in the Newspack UI components, and updates the UI font to Inter so it's consistent across all devices. 

Some specific fixes include:

* Fixing an alignment issue with the coupon field and adding error styles
* Fixing button spacing issues
* Updating the select2 colours (state/province dropdown) to match the Newspack UI theme.
* Removing the `!important` styles from `label`s and adding a WC-specific override instead.
* Fixing the transaction table font sizing
* Fixing spacing around the 'shipping address' toggle.

### How to test the changes in this Pull Request:

I've broken out the testing steps by each thing to review, but you could also just apply the PRs and run `npm run build`, and check each of these sections to make sure they look okay. This PR is also available on [the components test site](https://newspack-components-ui-demo.newspackstaging.com/).

#### Testing shipping toggle, select2 colours, and general spacing fixes:

1. Create a simple, non-virtual product so it can be shipped.
2. Add a checkout button block to a page and assign it to your non-virtual product.
3. Run through the checkout; confirm that the select2 now uses the same colour as the buttons, and not blue:

image

4. At the bottom of the 'Billing' section, note the appearance of the 'Different shipping address' toggle. Turn it on and fill out your shipping address and click 'Continue'.

image

image

5. On the next screen, note the spacing, especially for the Billing, Shipping, Payment headers. Also note the inconsistent font sizing in the Transaction Details table:

image

image

6. Apply this PR and [the block PR](https://github.com/Automattic/newspack-blocks/pull/1747), and run `npm run build` for each. 
7. Repeat the above testing steps and confirm that the spacing and sizing seems more consistent in each section.

image

image

image

image

#### Testing the coupon changes:

1. Navigate to WP Admin > WooCommerce > Settings, and enable coupons.
9. Create at least one coupon code under WP Admin > WooCommerce > Marketing.
10. Set up a product (subscription or simple), and add a checkout block button that is linked to it.
11. Run through the checkout process and note its appearance:

image

12. Apply this PR and [the corresponding block one](https://github.com/Automattic/newspack-blocks/pull/1747), and run `npm run build` for each.
13. Run through the checkout again; note the coupon form's appearance is closer to the mockups (no button alignment issue; better spacing). 
14. Try adding a fake coupon code or submitting the form without a code, and confirm you get an error message:

image

15. Add your real coupon code and confirm it's successfully applied, and the error styling goes away:

image

#### Testing button spacing issues

1. Set up a variable product, and add a checkout block button to a page that loads it.
2. In an incognito window (so you have to sign up), run through the checkout and note the button spacing -- specifically:
* Note the product variation buttons -- too much space above. 
* Check the spacing of buttons in the sign up form - there's too much on the bottom.

image

image

3. Apply this PR to the plugin & the associated block one, and run `npm run build`.
4. Repeat the checkout, and check the button spacing:

image

image

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by laurelfulford** [comment]
@Automattic/newspack-design This shouldn't introduce anything new/weird, it's mostly playing whack-a-mole to fix some style issues I noticed once PRs were combined. Just the same, I'd appreciate your eyes to make sure I haven't made things worse!!

**Review by chickenn00dle — CHANGES_REQUESTED** [review]
Nice work @laurelfulford!

The visual changes look good for the most part. I ran into a few issues though:

1. There is a jumping behavior when the error message appears whenever an invalid coupon is submitted:

https://github.com/Automattic/newspack-plugin/assets/17905991/6681af8e-0c1e-4592-8b16-cd739fa8618b

I remember running into this problem while working on Name Your Price support for checkout button block. The problem was with [using the jquery block method](https://github.com/Automattic/newspack-blocks/blob/e2a2719053d70371991e8413adf0b1853525fb7a/src/modal-checkout/index.js#L223-L229). The solution I used was to just stop using it altogether and [instead disable the input/add some css](https://github.com/Automattic/newspack-blocks/blob/fdb7b8728b6575ac69565728b449580af24fd903/src/modal-checkout/index.js#L283-L285) to make the button opaque when the processing class was present.

2. There is some strangeness with repeated prices in the variations modal when one or more of the variations has NYP enabled:

Screenshot 2024-05-30 at 11 12 38

3. Its worth pulling the latest changes from `epic/ras-acc` which contains a new Name Your Price input in the checkout modal for checkout button block. There are problem some spacing tweaks that need to be made with this as well to make it consistent with the rest of these changes.

**Comment by laurelfulford** [comment]
Thanks @chickenn00dle! 

I've fixed the error jump, and adjusted the spacing for NYP a bit and added the same error behaviour (so the label should be turning red when you add a bad price, too):

image

I'll better consolidate these styles when I move some of the checkout styles to the Newspack Blocks plugin after this lands 🙂 

I wasn't able to recreate the NYP + variable weirdness, though! This is what I get when I have more than one variation with NYP enabled:

image

Can you share a bit more about the settings you have to see that?

**Review by chickenn00dle — APPROVED** [review]
> There is some strangeness with repeated prices in the variations modal when one or more of the variations has NYP enabled

I dug into this and it looks like this was an issue with my local site. At some point while working on other NYP-related tasks, it looks like the suggested NYP text stored in the options table (`woocommerce_nyp_suggested_text`) ended up with a duplicate PRICE placeholder which was causing this strangeness. Deleting the option fixed the problem for me.

Thanks for addressing these other issues. This looks good to go now!

**Comment by laurelfulford** [comment]
Awesome, thanks @chickenn00dle!! 🙌 And I meant to add in the original comment: thank you for the tip to fix the coupon error weirdness! 

I'm going to go ahead and merge this one since it doesn't change how the design should look, it just fixes some issues with how different pieces came together. That way I can hopefully take care of some CSS reorganization today!

**Pull request merged**
