### PR TITLE
Refactor/wizards

### PR DESCRIPTION
**Pull request by adekbadek**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Refactors Support & Syndication Wizards to use the new `Wizard` component.

### How to test the changes in this Pull Request:

Visit Support & Syndication wizards, do a smoke test to verify they work as before

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Review by dkoo — APPROVED** [review]
Tested the Syndication and Support wizards with no issues. 👍

**Comment by yogeshbeniwal** [comment]
@adekbadek Is something wrong with release workflow, Many PRs like this are already released in v1.75.0 but then triggering another notification for lesser version number 1.72.0-hotfix.1.

**Comment by adekbadek** [comment]
Definitely something is off with the git tags, but the releases themselves are fine. I'll look into it.

**Comment by adekbadek** [comment]
This was caused by an erroneous hotfix release, which was created off `master` branch – https://github.com/Automattic/newspack-plugin/pull/1501. This way, a new hotfix release was created, which contained a chaotic set of changes (between last hotfix release and tip of `master`, something along these lines).

**Pull request merged**
