### PR TITLE
feat(esp-sync): sync membership data regardless of subscription

### PR DESCRIPTION
**Pull request by adekbadek**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

- Adds ESP-data syncing for all memberships, regardless of whether or not a membership is linked to a subscription
- Adds new ESP metadata fields:
    - `membership_plan` - the plan name
    - `membership_start_date`
    - `membership_end_date`
- Adds a `Newspack_Newsletters::get_applicable_fields` method, also added in #3352

### How to test the changes in this Pull Request:

1. In the Engagement wizard, "Email Service Provider (ESP) Advanced Settings" section, ensure "Sync contacts to ESP" is toggled on
2. Observe new fields listed: `Membership Plan`, `Current Membership Start Date`, `Current Membership End Date`
3. Toggle them on, and also ensure `Membership Status` is toggled on
4. Create a new memberships, with a new contact – observe it's synced to the ESP, with all the applicable fields

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1207471874427936

### CODE REVIEW

**Review by miguelpeixe — APPROVED** [review]
Tested well for memberships manually granted as well via paid subscription. 

My Mailchimp test account is hitting the limit of 30 merge fields per audience. Should we be concerned about that limit?

**Comment by adekbadek** [comment]
> My Mailchimp test account is hitting the limit of 30 merge fields per audience. Should we be concerned about that limit?

We could display a warning in the Engagement wizard, but I'm not sure if MC API can tell us something about the limit. Anyway, that's for another PR. For the record, currently there are 22 fields added by this plugin (`Newspack_Newsletters::get_all_metadata_fields`).

**Comment by miguelpeixe** [comment]
p1725549471491669/1725541457.029909-slack-C015W6BES8J

A bug was found in this implementation. The membership fields are "payment fields", [which are all cleared](https://github.com/Automattic/newspack-plugin/blob/67d566342681788955728de502fe5f2fc5f6a2d0/includes/reader-revenue/woocommerce/class-woocommerce-connection.php#L369-L382) when processed via `WooCommerce_Connection::get_contact_from_customer()` or `WooCommerce_Connection::get_contact_from_order()`. This will happen on every manual sync, new donation, or subscription purchase, erasing any membership-related fields that are not part of the order being processed.

This will defeat the purpose of having persisted membership data regardless of subscription.

**Comment by adekbadek** [comment]
@miguelpeixe – the bug you mention will be fixed in https://github.com/Automattic/newspack-plugin/pull/3419

**Pull request merged**
