### PR TITLE
feat(webhooks): endpoint management ui

### PR DESCRIPTION
**Pull request by miguelpeixe**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Adds UI for managing webhook endpoints:

image

image

Captura de Tela 2022-12-16 às 15 37 53

Captura de Tela 2022-12-16 às 15 38 34

image\

image

### How to test the changes in this Pull Request:

1. Check out this branch, visit the "Connections" wizard and confirm nothing is changed
2. Add the experimental flag to your config: `define( 'NEWSPACK_EXPERIMENTAL_WEBHOOKS', true );`
3. Refresh the wizard and confirm you see the Webhook Endpoints section at the end
4. Confirm you have AMP Plus, RAS, and Newspack logging enabled:
```php
define( 'NEWSPACK_AMP_PLUS_ENABLED', true );
define( 'NEWSPACK_EXPERIMENTAL_READER_ACTIVATION', true );
define( 'NEWSPACK_LOG_LEVEL', 2 );
```
5. Create your first global webhook endpoint pointing to an URL provided by https://webhook.site/ (visit the site to get one)
6. Create a second webhook endpoint pointing to a non-existent URL
7. In incognito, register a new reader through a RAS flow
8. Refresh the wizard page, click the `info` icon and confirm the webhook requests are scheduled
9. Wait until they are sent, confirm you receive the request and the wizard table is also updated
10. Create a new endpoint and test different test sends before saving. Confirm you receive appropriate error messages.
11. Edit the existing endpoint to a different URL/actions and confirm it's saved
12. Delete the endpoint and refresh to confirm the endpoint is deleted

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by thomasguillot** [comment]
@miguelpeixe I pushed a few changes in https://github.com/Automattic/newspack-plugin/pull/2197/commits/29f9e98d088392eb0adf5ec3cffd9a0d09bfd4c2

I have a few questions/requests.

Screenshot 2022-12-21 at 13 09 42

Could we move the actions behind a `moreVertical` button and a `popover`?

Screenshot 2022-12-21 at 14 37 32
Screenshot 2022-12-21 at 14 37 44

Could we move the confirmation messages (delete, disable) to an actual `Modal` rather than the browser's modal?

Screenshot 2022-12-21 at 14 38 37

I think we could use a `ToggleGroup` for the actions and only display the checkboxes when Global isn't toggled. The If message ("If this endpoint is not global, select which actions should trigger this endpoint:") would then be unnecessary.

**Comment by miguelpeixe** [comment]
Thank you for the redesign!

c83b348b4af0576ad4b3978bf950bb645803083d adds a Popover for actions:

image

c8e82d2edfd4c0e6cc8f7334c7885f95f2a47ca8 adds a `ConfirmationModal` for destructive actions:

image

> I think we could use a ToggleGroup for the actions and only display the checkboxes when Global isn't toggled. The If message ("If this endpoint is not global, select which actions should trigger this endpoint:") would then be unnecessary.

My intention is to be very clear that global means that all the actions listed below will trigger the endpoint. It also serves to clarify what are the available actions, sort of a hint of documentation. This will likely change and be improved soon to better document how to use the actions and their payload.

**Comment by thomasguillot** [comment]
thank you for the quick fixes, @miguelpeixe. I pushed some more (very small) changes: https://github.com/Automattic/newspack-plugin/pull/2197/commits/5d97bc1928011f8ba38ec766f1e2ad04dcd3053c

**Comment by thomasguillot** [comment]
> My intention is to be very clear that global means that all the actions listed below will trigger the endpoint. It also serves to clarify what are the available actions, sort of a hint of documentation. This will likely change and be improved soon to better document how to use the actions and their payload.

Ok no worries. I have a requests then 🙂

Can we make sure the "if" text is hidden when it's loading? It looks a bit odd at the moment.

Screenshot 2022-12-21 at 16 23 46

In fact, maybe we can the entire content of the actions whilst it's loading.

**Comment by miguelpeixe** [comment]
Sure! But I'm curious to understand the context in which the edit modal is opened before the actions are finished loading. They are fetched on page load.

27a34150eec748cf96c74736a76e7aad5a5c5dab makes sure to only display further action options if there are available actions.

**Comment by thomasguillot** [comment]
Hmm weird, I was able to open the modal when it was still loading. Not quite sure how I did it 😅

**Comment by miguelpeixe** [comment]
I couldn't identify anything that could be hanging the request, but it's something to keep an eye on.

**Review by leogermani — APPROVED** [review]
Working as described!

**Pull request merged**
