### PR TITLE
fix: salesforce opportunities should be set to closed/won instead of new

### PR DESCRIPTION
**Pull request by dkoo**
Brought to our attention by TRNN, this is a requirement for them to use the roll-up reports they use to track donations.

### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Makes some changes to the Salesforce sync functionality to make the synced data work better with NPSP roll-up reports, as requested by TRNN.

### How to test the changes in this Pull Request:

1. Ensure that you have a Salesforce developer account connected to your Newspack site ([instructions here](https://newspack.pub/support/reader-revenue/salesforce/)).
2. Make a donation through the Donate block and make sure to fill in all contact info in the checkout form.
3. Log into Salesforce and go to **Sales Console > Opportunities** to find the data synced from WooCommerce. Click on the Opportunity that corresponds to your order, then click the **Details** tab.
4. Confirm that the "Stage" for the opportunity is set to "Closed Won" (visible at the top of the opportunity screen, and in the Details tab).
5. If the Salesforce instance is [NPSP](https://www.salesforce.org/trial/npsp/), confirm that there's a "Primary Contact" field set with the contact info matching what you inputted in WooCommerce.
6. Under **Contact Roles**, confirm that there's a contact listed as Primary with a role of "Hard Credit" (there may be two contact roles for the same contact, the other being "Donor", but this is expected). Click on the contact name, then the Details tab, and confirm that the contact details match what you entered in the WooCommerce checkout form.

Note: TRNN has tested and confirmed that the fix works as desired on their NPSP account.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by dkoo** [comment]
Setting this as draft as I'm awaiting confirmation from TRNN that this fixes the issues they're experiencing with their reports.

**Comment by dkoo** [comment]
This is missing one piece which may or may not be even possible in the Salesforce REST API ([details here](https://developer.salesforce.com/forums?communityId=09aF00000004HMGIA2#!/feedtype=SINGLE_QUESTION_DETAIL&dc=APIs_and_Integration&criteria=OPENQUESTIONS&id=9062I000000IR9JQAW)), but the included fixes should bring TRNN one step closer to their goals.

**Comment by dkoo** [comment]
> This is missing one piece which may or may not be even possible in the Salesforce REST API ([details here](https://developer.salesforce.com/forums?communityId=09aF00000004HMGIA2#!/feedtype=SINGLE_QUESTION_DETAIL&dc=APIs_and_Integration&criteria=OPENQUESTIONS&id=9062I000000IR9JQAW)), but the included fixes should bring TRNN one step closer to their goals.

Update: figured this out, added in 2a2875c

**Review by jeffersonrabb — APPROVED** [review]
Tested and verified.

**Pull request merged**
