### PR TITLE
Remove material icons and rework Analytics and Ads Wizards

### PR DESCRIPTION
**Pull request by thomasguillot**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR entirely removes Material npm packages so I had to reorganise/rework some of the components (Plugin Installer, Waiting) and wizards (Analytics, Ads)

### How to test the changes in this Pull Request:

1. Switch to this branch
2. See if you can find any Material icons left
3. Check the various wizards

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Review by dkoo — CHANGES_REQUESTED** [review]
Changes look good and I didn't run into any issues, but we should do a quick re-test after fixing the conflicts with `newspack-components`.

**Comment by thomasguillot** [comment]
> Changes look good and I didn't run into any issues, but we should do a quick re-test after fixing the conflicts with `newspack-components`.

Conflicts should be resolved. https://github.com/Automattic/newspack-plugin/pull/982/commits/4c6f497bc99d5b79cb851de033b6e704093301bf

**Comment by dkoo** [comment]
Still seeing conflicts with `package.json` in `newspack-components`, seems like just a version bump for that package?

**Comment by thomasguillot** [comment]
> Still seeing conflicts with `package.json` in `newspack-components`, seems like just a version bump for that package?

Hmmm yes, weird. Anyway... fixed: https://github.com/Automattic/newspack-plugin/pull/982/commits/8313519305bf1a466fb127634534fc90f4cca444

**Review by dkoo — APPROVED** [review]
Re-tested the components demo page, all looks good!

**Pull request merged**
