### PR TITLE
Use CSS grid to implement the Muriel grid

### PR DESCRIPTION
**Pull request by jffng**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Introduces an approach to address #171 using CSS grid to size and position components to the Muriel grid.

Before:
image

After: 
image

### How to test the changes in this Pull Request:

1. `npm ci && npm run clean && npm run build:webpack`
2. Navigate to `Newspack -> Components demo`
3. Verify that the components align to the grid at all viewport sizes

Note that these changes attempt to scope this to the `Components demo` page only. Thus having to add the `muriel-grid-item` classname to each card component in the components demo.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by jffng** [comment]
Ah yeah. The grid actually uses a `1040px` breakpoint, made that fix and pushed. 

> Did you scope to the Components page purely for demo purposes? After this PR ships, would you suggest we apply the muriel-grid-item styling to all Card components?

Yes and yes. I wanted to make sure we were comfortable with the approach -- it requires a grid container class to be applied to wherever the card components are used.

I went with a mixin so we could just apply it to existing container classes as necessary. But if it turns out that cards are used everywhere, maybe we should use a utility class instead to avoid a bunch of duplicate css. I could work on this next and see how it goes.

**Comment by claudiulodro** [comment]
It might be easiest to just add the `muriel-grid-item` class to [the Card component.](https://github.com/Automattic/newspack-plugin/blob/master/assets/components/src/card/index.js#L26)

**Comment by jffng** [comment]
@claudiulodro totally. It would just require a containing element to have grid styles also.

Just pushed a change that implements this using a grid container component. Let me know if that's an acceptable approach.

**Comment by sonjaleix** [comment]
@jffng This is looking great now. I'm getting one alignment issue for some of the action cards on mobile: 
Screenshot 2019-07-10 12 58 03

Otherwise all components are perfectly aligning to the grid in all viewports.

**Comment by jffng** [comment]
@sonjaleix thanks for catching that, pushed a fix.

**Comment by sonjaleix** [comment]
Thanks @jffng! The issue with the action card on mobile looks great now!

I'm not sure if you've applied the changes only to the components screen. If so, we might want to merge or see how they apply to the other screens and wizards too. 
We still need to test how this looks for the Setup screens and individual wizard.

One other specific thing we will probably have to adjust, is the odd grid on the Newspack dashboard: /wp-admin/admin.php?page=newspack

See grid dashboard (homescreen) blocks and how they align in the grid in design: 
Screenshot 2019-07-10 15 33 41
Screenshot 2019-07-10 15 33 30

**Comment by claudiulodro** [comment]
I've updated the wizards and checklists to use the grid in https://github.com/Automattic/newspack-plugin/pull/172/commits/4e58ddfc960b982d322b99d1cd134beb0aa5d8b4. They should all line up nicely now. 

The only exception is the dashboard which is going to need some CSS fine-tuning to play nicely with the grid:
localhost_wp-admin_admin php_page=newspack (2)

I can handle it after this is merged.

**Pull request merged**
