### PR TITLE
fix: show campaigns with pending and future status in UI

### PR DESCRIPTION
**Pull request by dkoo**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Current campaign UI only shows campaign posts that have `publish` and `draft` statuses. This would cause posts with the `pending` or `future` status to be dropped before being rendered in the UI.

This PR, along with https://github.com/Automattic/newspack-popups/pull/356, shows pending drafts under the "Draft" header and scheduled campaigns under the "Inactive" header, with a corresponding "Pending review" or "Scheduled" label for each.

Screen Shot 2020-12-18 at 3 36 46 PM

Closes https://github.com/Automattic/newspack-popups/issues/355.

### How to test the changes in this Pull Request:

1. On `master` for both this plugin and in Campaigns, create a new overlay or inline campaign and save it as a draft with the "Pending review" option enabled:

Screen Shot 2020-12-18 at 3 37 56 PM

2. ~Go to **Newspack > Campaigns** and observe that the campaign is not rendered anywhere.~ Because of https://github.com/Automattic/newspack-popups/pull/399, you'll actually see these campaigns in the list, but they'll appear as drafts.
3. Check out this branch and run `npm run build`.
4. In **Newspack > Campaigns** under the Campaigns tab confirm that you now see the pending campaign with the "Draft" color with a "Pending review" label.
5. Edit the campaign again. Change the publish date to some date in the future and click "Schedule" button to schedule it for future publishing (the pending option is automatically disabled with the `future` and `publish` statuses).
6. Refresh the **Newspack > Campaigns** page. Confirm that the campaign still appears with the "Draft" color with a "Scheduled" label.
7. ~Turn on Test mode for the campaign and refresh the **Newspack > Campaigns** page. Confirm that the campaign still appears with the "Draft" color with a "Scheduled" label.~ There's no longer a test mode, so you can skip this step.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Review by jeffersonrabb — CHANGES_REQUESTED** [review]
Noted two issues:

- A scheduled Campaign in Test Mode does not appear in the wizard.
- Not sure if this is related to this branch, but the filter seems to reflect the options in the first tab that was loaded even after switching tabs. This often means the filter options are not accurate for a different tab, and this makes it possible to choose an option that shows no results.

**Comment by jeffersonrabb** [comment]
> * Not sure if this is related to this branch, but the filter seems to reflect the options in the first tab that was loaded even after switching tabs. This often means the filter options are not accurate for a different tab, and this makes it possible to choose an option that shows no results.

This wasn't related to this branch, and is resolved in https://github.com/Automattic/newspack-plugin/pull/761. That PR should be merged before this one is reviewed again, as it impacts testing.

**Comment by dkoo** [comment]
> This wasn't related to this branch, and is resolved in #761. That PR should be merged before this one is reviewed again, as it impacts testing.

I reviewed #761 and approved.

> A scheduled Campaign in Test Mode does not appear in the wizard.

Should probably hold this given https://github.com/Automattic/newspack-plugin/pull/776.

**Comment by dkoo** [comment]
This branch is now updated with the latest UI changes, and this issue is now resolved:

> A scheduled Campaign in Test Mode does not appear in the wizard.

Scheduled/future campaigns in Test mode will now appear in the list as drafts (since test mode campaigns will only render on the front-end if published and the user is logged in).

**Comment by dkoo** [comment]
This has been updated and can be re-tested now that #809 has landed.

**Review by jeffersonrabb — APPROVED** [review]
🚢

**Pull request merged**
