### PR TITLE
feat: support manual-only placement

### PR DESCRIPTION
**Pull request by jeffersonrabb**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Adds Manual Placement UI to the Campaigns Wizard. Test with https://github.com/Automattic/newspack-popups/pull/373

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Review by adekbadek — APPROVED** [review]
All good. WDYT about adding a badge to manual campaigns, so they are easily discernible on the campaigns list?

**Comment by jeffersonrabb** [comment]
> WDYT about adding a badge to manual campaigns, so they are easily discernible on the campaigns list?

Good idea, added in https://github.com/Automattic/newspack-plugin/pull/796/commits/0eec21ab84f13bb7d199e8099b585c6cbefd6a78. 

I'll also wait for https://github.com/Automattic/newspack-plugin/pull/797 to land, then add "Manual Placement" to the new campaign `PopOver`. Placing this PR on hold until then.

**Review by adekbadek — APPROVED** [review]

**Comment by jeffersonrabb** [comment]
@thomasguillot I added support for Manual Placement Campaigns in https://github.com/Automattic/newspack-plugin/pull/796/commits/b63611e9e6cf3f80316a811bfd22a990b62301b2, but the length of the `MenuItem` text breaks the `PopOver`. Do you have a suggestion for how to resolve?

Screen Shot 2021-01-11 at 8 59 59 AM

**Comment by thomasguillot** [comment]
@jeffersonrabb remove "Campaign" it's a bit repetitive and we already know we're adding a Campaigns

**Comment by jeffersonrabb** [comment]
> @jeffersonrabb remove "Campaign" it's a bit repetitive and we already know we're adding a Campaigns

@thomasguillot I assume I should remove from all items, not just the Manual one?

**Comment by thomasguillot** [comment]
@jeffersonrabb Yes 😊

**Comment by jeffersonrabb** [comment]
Added "Manual" to the list of options seen after clicking Add New. Note that Automattic/newspack-popups#373 will need to be pulled again for this to work.

**Review by adekbadek — APPROVED** [review]

**Pull request merged**
