### PR TITLE
Disable local lists in the newsletters wizard

### PR DESCRIPTION
**Pull request by leogermani**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Disables the edit of title and description from the list where we select the active Subscription Lists.

Since they are created locally, there is no need to edit the title and description again. Instead of allowing edits, link to the edit page.

### How to test the changes in this Pull Request:

1. Go to Newsletters > Engagement > Newsletters
2. Make sure there are no changes in the UI and no warnings in the terminal
3. Checkout [this PR](https://github.com/Automattic/newspack-newsletters/pull/1035) in the Newsletter plugin
1.Set up Mailchimp or AC as provider
4. Go to Newsletters > Lists and create a couple of lists
5. Go to Newsletters > Engagement > Newsletters
6. Go to the "Subscription Lists" section
7. Make sure the Local lists are marked as such and you can't edit their title and description
8. Make sure the edit links points to the righ place
9. Make sure you are still able to enable/disable them
10. And make sure they are still working in the rest of the application (registration form, etc)

Captura de tela de 2022-11-28 11-52-38

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Review by miguelpeixe — APPROVED** [review]
I pushed some UI tweaks on 2b11c04f44b055fe04aa73c85e12a201c65e079f to use the `<ActionCard />` instead of `<Card />`. It also removes the disabled inputs and uses the `actionText` prop for an aligned **Edit** link:

image

Feel free to revert if you don't think it's a good fit!

**Comment by leogermani** [comment]
Thanks, I'll test with the removed disabled inputs, because on the Newsletters settings screen I had to add a hidden field other wise the Options were not saved because the list was considered invalid

**Comment by miguelpeixe** [comment]
It worked without issues for me. The input existence doesn't affect the request payload, it still includes all the list metadata (name and description).

**Comment by leogermani** [comment]
Thanks @miguelpeixe , it looks much better now :)

**Pull request merged**
