### PR TITLE
feat: allow external links in dashboard via a filter

### PR DESCRIPTION
**Pull request by adekbadek**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Allows the dashboard links to be filterable, so a plugin may add something.

### How to test the changes in this Pull Request:

Ping me for specific instructions. 

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Review by leogermani — CHANGES_REQUESTED** [review]
I'm able to add a new item using the filter. I can't choose the icon though. Passing `is_external` correctly opens it in a new window.

I think we just need to add a doc block to the filter and make sure to document this new accepted property

**Comment by adekbadek** [comment]
Added a doc comment in aeb1d7631cc94040813bbd5d44ebc99fa949e140. Setting the icon is not implemented ATM, the icon will fall back to the question mark.

**Review by leogermani — APPROVED** [review]
> icon will fall back to the question mark.

In my case the fallback was the "plugin" icon

**Comment by adekbadek** [comment]
> In my case the fallback was the "plugin" icon

Ah that's correct! I've been testing with an item with `support` slug, which is already mapped to the question mark icon.

**Pull request merged**
